declare const enum bsr_existingusetypeofproposedworkchoic {
  Workwhichincreasesordecreasestheexternalheightorwidthofthehigherriskbuilding = 760810000,
  Workwhichchangesthenumberofstoreysthehigherriskbuildinghasincludingaddingorremovingamezzanineorgalleryfloor = 760810001,
  Workwhichchangesthenumberofflatsorresidentialroomscontainedinthehigherriskbuilding = 760810002,
  Workwhichchangesthenumberoforwidthofthestaircasesinahigherriskbuildingorwhichchangesthenumberoforwidthofanyotherescaperoutewithinthebuilding = 760810003,
  Worktotheexternalwallofahigherriskbuildingexcludingworkormaterialsofadescriptionspecifiedinregulation73ofthe2010Regulations = 760810004,
  WorkwhichchangestheinternallayoutofahighriskbuildingWorkwhichaffectsthepassivefiresafetymeasuresinahigherriskbuilding = 760810005,
  Workwhichaffectstheactiveiresafetymeasuresinahigherriskbuilding = 760810006,
  WorkwhichaffectsthecommonpartsofahigherriskbuildingincludingtheexternalwallnototherwisefallingwithincategoryA = 760810007,
  WorkwhichdoesnotfallwithincategoryA = 760810008,
}
