declare namespace Form.bsr_buildingdetails.Main {
  namespace Information {
    namespace Tabs {
      interface tab1 extends Xrm.SectionCollectionBase {
        get(name: "_section_557"): Xrm.PageSection;
        get(name: "statusdetails"): Xrm.PageSection;
        get(name: "tab1_section1"): Xrm.PageSection;
        get(name: "tab1_section_10"): Xrm.PageSection;
        get(name: "tab1_section_12"): Xrm.PageSection;
        get(name: "tab1_section_14"): Xrm.PageSection;
        get(name: "tab1_section_15"): Xrm.PageSection;
        get(name: "tab1_section_16"): Xrm.PageSection;
        get(name: "tab1_section_17"): Xrm.PageSection;
        get(name: "tab1_section_18"): Xrm.PageSection;
        get(name: "tab1_section_3"): Xrm.PageSection;
        get(name: "tab1_section_4"): Xrm.PageSection;
        get(name: "tab1_section_5"): Xrm.PageSection;
        get(name: "tab1_section_6"): Xrm.PageSection;
        get(name: "tab1_section_7"): Xrm.PageSection;
        get(name: "tab1_section_8"): Xrm.PageSection;
        get(name: "tab1_section_9"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_3 extends Xrm.SectionCollectionBase {
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_mdt extends Xrm.SectionCollectionBase {
        get(name: "tab_mdt_section_3"): Xrm.PageSection;
        get(name: "tab_projectbriefs"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_staged_application extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "bsr_address1_city"): Xrm.Attribute<string>;
      get(name: "bsr_address1_line1"): Xrm.Attribute<string>;
      get(name: "bsr_address1_line2"): Xrm.Attribute<string>;
      get(name: "bsr_address1_postalcode"): Xrm.Attribute<string>;
      get(name: "bsr_bcapplicationid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
      get(name: "bsr_bdrcaseofficer"): Xrm.LookupAttribute<"systemuser">;
      get(name: "bsr_builddetailscancellationreason"): Xrm.OptionSetAttribute<bsr_buildingdetailscancellationreason>;
      get(name: "bsr_builddetailscompletionreason"): Xrm.OptionSetAttribute<bsr_buildingdetailscompletionreason>;
      get(name: "bsr_builddetailsinvalidreason"): Xrm.OptionSetAttribute<bsr_buildingdetailsinvalidreason>;
      get(name: "bsr_buildingaddressmanual"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_buildingdetailsreference"): Xrm.Attribute<string>;
      get(name: "bsr_buildingdetailsstatus"): Xrm.OptionSetAttribute<bsr_statusofthebuildingdetailsrecord>;
      get(name: "bsr_buildingeasting"): Xrm.NumberAttribute;
      get(name: "bsr_buildingnorthing"): Xrm.NumberAttribute;
      get(name: "bsr_buildingregcompliance"): Xrm.Attribute<string>;
      get(name: "bsr_buildingregistrationnumber"): Xrm.Attribute<string>;
      get(name: "bsr_buildoverwithin3mofcentrelineflow"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_changecontrollog"): Xrm.Attribute<string>;
      get(name: "bsr_changecontrolplan"): Xrm.Attribute<string>;
      get(name: "bsr_changeofusedescription"): Xrm.Attribute<string>;
      get(name: "bsr_competencedeclaration"): Xrm.Attribute<string>;
      get(name: "bsr_completeddate"): Xrm.DateAttribute;
      get(name: "bsr_constructioncontrolplan"): Xrm.Attribute<string>;
      get(name: "bsr_currentheight"): Xrm.NumberAttribute;
      get(name: "bsr_currentnonresidentialunits"): Xrm.NumberAttribute;
      get(name: "bsr_currentnumberofresidentialunits"): Xrm.NumberAttribute;
      get(name: "bsr_currentnumberstoreys"): Xrm.NumberAttribute;
      get(name: "bsr_currentprimaryuse"): Xrm.MultiSelectOptionSetAttribute<bsr_primaryusechoice>;
      get(name: "bsr_currentstoreyuse"): Xrm.Attribute<string>;
      get(name: "bsr_existingbuildingworkid"): Xrm.LookupAttribute<"bsr_bcworkcategory">;
      get(name: "bsr_existtypeworkproposal"): Xrm.MultiSelectOptionSetAttribute<bsr_existingusetypeofproposedworkchoic>;
      get(name: "bsr_firecompliancedoc"): Xrm.Attribute<string>;
      get(name: "bsr_fireemergencyfiles"): Xrm.Attribute<string>;
      get(name: "bsr_height"): Xrm.NumberAttribute;
      get(name: "bsr_hrbworkid"): Xrm.LookupAttribute<"bsr_bcworkcategory">;
      get(name: "bsr_ischangeofuse"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_iscompletedworks"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_localenactment"): Xrm.Attribute<string>;
      get(name: "bsr_morplan"): Xrm.Attribute<string>;
      get(name: "bsr_name"): Xrm.Attribute<string>;
      get(name: "bsr_newdrainorsewer"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_newdrainorsewerlocation"): Xrm.Attribute<string>;
      get(name: "bsr_nonhrb"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_numbernonresidentialunits"): Xrm.NumberAttribute;
      get(name: "bsr_numberresidentialunits"): Xrm.NumberAttribute;
      get(name: "bsr_numberstoreys"): Xrm.NumberAttribute;
      get(name: "bsr_partialcompletion"): Xrm.Attribute<any>;
      get(name: "bsr_partialcompletionstrategy"): Xrm.Attribute<string>;
      get(name: "bsr_partialoccupationplan"): Xrm.Attribute<string>;
      get(name: "bsr_pgo"): Xrm.Attribute<string>;
      get(name: "bsr_pgoreferencenumber"): Xrm.Attribute<string>;
      get(name: "bsr_plannedbuildtime"): Xrm.NumberAttribute;
      get(name: "bsr_planningreferencenumber"): Xrm.Attribute<string>;
      get(name: "bsr_primaryuse"): Xrm.MultiSelectOptionSetAttribute<bsr_primaryusechoice>;
      get(name: "bsr_remainingwork"): Xrm.Attribute<string>;
      get(name: "bsr_sitelocationplan"): Xrm.Attribute<string>;
      get(name: "bsr_sitesharedservices"): Xrm.OptionSetAttribute<bsr_sitesharedserviceschoice>;
      get(name: "bsr_sitesharedservicesdetails"): Xrm.Attribute<string>;
      get(name: "bsr_sitesharedservicesurl"): Xrm.Attribute<string>;
      get(name: "bsr_storeyuse"): Xrm.Attribute<string>;
      get(name: "bsr_submissiondate"): Xrm.DateAttribute;
      get(name: "bsr_tellusaboutyourdrainageprecautions"): Xrm.Attribute<string>;
      get(name: "bsr_tellusaboutyourdrainageprecautionsdoc"): Xrm.Attribute<string>;
      get(name: "bsr_workdescription"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_informationtracker">;
      get(name: "Subgrid_new_2"): Xrm.SubGridControl<"bsr_drawingsandplans">;
      get(name: "Subgrid_new_3"): Xrm.SubGridControl<"bsr_mdtproject">;
      get(name: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
      get(name: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_buildingcontrollifecycle">;
      get(name: "Subgrid_projectbriefs"): Xrm.SubGridControl<"bsr_projectbriefs">;
      get(name: "bsr_address1_city"): Xrm.StringControl;
      get(name: "bsr_address1_line1"): Xrm.StringControl;
      get(name: "bsr_address1_line2"): Xrm.StringControl;
      get(name: "bsr_address1_postalcode"): Xrm.StringControl;
      get(name: "bsr_bcapplicationid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_bdrcaseofficer"): Xrm.LookupControl<"systemuser">;
      get(name: "bsr_builddetailscancellationreason"): Xrm.OptionSetControl<bsr_buildingdetailscancellationreason>;
      get(name: "bsr_builddetailscompletionreason"): Xrm.OptionSetControl<bsr_buildingdetailscompletionreason>;
      get(name: "bsr_builddetailsinvalidreason"): Xrm.OptionSetControl<bsr_buildingdetailsinvalidreason>;
      get(name: "bsr_buildingaddressmanual"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_buildingdetailsreference"): Xrm.StringControl;
      get(name: "bsr_buildingeasting"): Xrm.NumberControl;
      get(name: "bsr_buildingnorthing"): Xrm.NumberControl;
      get(name: "bsr_buildingregcompliance"): Xrm.StringControl;
      get(name: "bsr_buildingregistrationnumber"): Xrm.StringControl;
      get(name: "bsr_buildoverwithin3mofcentrelineflow"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_changecontrollog"): Xrm.StringControl;
      get(name: "bsr_changecontrolplan"): Xrm.StringControl;
      get(name: "bsr_changeofusedescription"): Xrm.StringControl;
      get(name: "bsr_competencedeclaration"): Xrm.StringControl;
      get(name: "bsr_completeddate"): Xrm.DateControl;
      get(name: "bsr_constructioncontrolplan"): Xrm.StringControl;
      get(name: "bsr_currentheight"): Xrm.NumberControl;
      get(name: "bsr_currentnonresidentialunits"): Xrm.NumberControl;
      get(name: "bsr_currentnumberofresidentialunits"): Xrm.NumberControl;
      get(name: "bsr_currentnumberstoreys"): Xrm.NumberControl;
      get(name: "bsr_currentprimaryuse"): Xrm.MultiSelectOptionSetControl<bsr_primaryusechoice>;
      get(name: "bsr_currentstoreyuse"): Xrm.StringControl;
      get(name: "bsr_existingbuildingworkid"): Xrm.LookupControl<"bsr_bcworkcategory">;
      get(name: "bsr_existtypeworkproposal"): Xrm.MultiSelectOptionSetControl<bsr_existingusetypeofproposedworkchoic>;
      get(name: "bsr_firecompliancedoc"): Xrm.StringControl;
      get(name: "bsr_fireemergencyfiles"): Xrm.StringControl;
      get(name: "bsr_height"): Xrm.NumberControl;
      get(name: "bsr_hrbworkid"): Xrm.LookupControl<"bsr_bcworkcategory">;
      get(name: "bsr_ischangeofuse"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_iscompletedworks"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_localenactment"): Xrm.StringControl;
      get(name: "bsr_morplan"): Xrm.StringControl;
      get(name: "bsr_name"): Xrm.StringControl;
      get(name: "bsr_newdrainorsewer"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_newdrainorsewerlocation"): Xrm.StringControl;
      get(name: "bsr_nonhrb"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_numbernonresidentialunits"): Xrm.NumberControl;
      get(name: "bsr_numberresidentialunits"): Xrm.NumberControl;
      get(name: "bsr_numberstoreys"): Xrm.NumberControl;
      get(name: "bsr_partialcompletion"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "bsr_partialcompletionstrategy"): Xrm.StringControl;
      get(name: "bsr_partialoccupationplan"): Xrm.StringControl;
      get(name: "bsr_pgo"): Xrm.StringControl;
      get(name: "bsr_pgoreferencenumber"): Xrm.StringControl;
      get(name: "bsr_plannedbuildtime"): Xrm.NumberControl;
      get(name: "bsr_planningreferencenumber"): Xrm.StringControl;
      get(name: "bsr_primaryuse"): Xrm.MultiSelectOptionSetControl<bsr_primaryusechoice>;
      get(name: "bsr_remainingwork"): Xrm.StringControl;
      get(name: "bsr_sitelocationplan"): Xrm.StringControl;
      get(name: "bsr_sitesharedservices"): Xrm.OptionSetControl<bsr_sitesharedserviceschoice>;
      get(name: "bsr_sitesharedservicesdetails"): Xrm.StringControl;
      get(name: "bsr_sitesharedservicesurl"): Xrm.StringControl;
      get(name: "bsr_storeyuse"): Xrm.StringControl;
      get(name: "bsr_submissiondate"): Xrm.DateControl;
      get(name: "bsr_tellusaboutyourdrainageprecautions"): Xrm.StringControl;
      get(name: "bsr_tellusaboutyourdrainageprecautionsdoc"): Xrm.StringControl;
      get(name: "bsr_workdescription"): Xrm.StringControl;
      get(name: "header_bsr_buildingdetailsstatus"): Xrm.OptionSetControl<bsr_statusofthebuildingdetailsrecord>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "tab1"): Xrm.PageTab<Tabs.tab1>;
      get(name: "tab_3"): Xrm.PageTab<Tabs.tab_3>;
      get(name: "tab_mdt"): Xrm.PageTab<Tabs.tab_mdt>;
      get(name: "tab_staged_application"): Xrm.PageTab<Tabs.tab_staged_application>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "bsr_address1_city"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_address1_line1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_address1_line2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_address1_postalcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_bcapplicationid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
    getAttribute(attributeName: "bsr_bdrcaseofficer"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "bsr_builddetailscancellationreason"): Xrm.OptionSetAttribute<bsr_buildingdetailscancellationreason>;
    getAttribute(attributeName: "bsr_builddetailscompletionreason"): Xrm.OptionSetAttribute<bsr_buildingdetailscompletionreason>;
    getAttribute(attributeName: "bsr_builddetailsinvalidreason"): Xrm.OptionSetAttribute<bsr_buildingdetailsinvalidreason>;
    getAttribute(attributeName: "bsr_buildingaddressmanual"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_buildingdetailsreference"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_buildingdetailsstatus"): Xrm.OptionSetAttribute<bsr_statusofthebuildingdetailsrecord>;
    getAttribute(attributeName: "bsr_buildingeasting"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_buildingnorthing"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_buildingregcompliance"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_buildingregistrationnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_buildoverwithin3mofcentrelineflow"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_changecontrollog"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_changecontrolplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_changeofusedescription"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_competencedeclaration"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_completeddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_constructioncontrolplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_currentheight"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_currentnonresidentialunits"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_currentnumberofresidentialunits"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_currentnumberstoreys"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_currentprimaryuse"): Xrm.MultiSelectOptionSetAttribute<bsr_primaryusechoice>;
    getAttribute(attributeName: "bsr_currentstoreyuse"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_existingbuildingworkid"): Xrm.LookupAttribute<"bsr_bcworkcategory">;
    getAttribute(attributeName: "bsr_existtypeworkproposal"): Xrm.MultiSelectOptionSetAttribute<bsr_existingusetypeofproposedworkchoic>;
    getAttribute(attributeName: "bsr_firecompliancedoc"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_fireemergencyfiles"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_height"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_hrbworkid"): Xrm.LookupAttribute<"bsr_bcworkcategory">;
    getAttribute(attributeName: "bsr_ischangeofuse"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_iscompletedworks"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_localenactment"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_morplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_newdrainorsewer"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_newdrainorsewerlocation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_nonhrb"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_numbernonresidentialunits"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_numberresidentialunits"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_numberstoreys"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_partialcompletion"): Xrm.Attribute<any>;
    getAttribute(attributeName: "bsr_partialcompletionstrategy"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_partialoccupationplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_pgo"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_pgoreferencenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_plannedbuildtime"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_planningreferencenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_primaryuse"): Xrm.MultiSelectOptionSetAttribute<bsr_primaryusechoice>;
    getAttribute(attributeName: "bsr_remainingwork"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sitelocationplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sitesharedservices"): Xrm.OptionSetAttribute<bsr_sitesharedserviceschoice>;
    getAttribute(attributeName: "bsr_sitesharedservicesdetails"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sitesharedservicesurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_storeyuse"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_submissiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_tellusaboutyourdrainageprecautions"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_tellusaboutyourdrainageprecautionsdoc"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_workdescription"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_informationtracker">;
    getControl(controlName: "Subgrid_new_2"): Xrm.SubGridControl<"bsr_drawingsandplans">;
    getControl(controlName: "Subgrid_new_3"): Xrm.SubGridControl<"bsr_mdtproject">;
    getControl(controlName: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_buildingcontrollifecycle">;
    getControl(controlName: "Subgrid_projectbriefs"): Xrm.SubGridControl<"bsr_projectbriefs">;
    getControl(controlName: "bsr_address1_city"): Xrm.StringControl;
    getControl(controlName: "bsr_address1_line1"): Xrm.StringControl;
    getControl(controlName: "bsr_address1_line2"): Xrm.StringControl;
    getControl(controlName: "bsr_address1_postalcode"): Xrm.StringControl;
    getControl(controlName: "bsr_bcapplicationid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_bdrcaseofficer"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "bsr_builddetailscancellationreason"): Xrm.OptionSetControl<bsr_buildingdetailscancellationreason>;
    getControl(controlName: "bsr_builddetailscompletionreason"): Xrm.OptionSetControl<bsr_buildingdetailscompletionreason>;
    getControl(controlName: "bsr_builddetailsinvalidreason"): Xrm.OptionSetControl<bsr_buildingdetailsinvalidreason>;
    getControl(controlName: "bsr_buildingaddressmanual"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_buildingdetailsreference"): Xrm.StringControl;
    getControl(controlName: "bsr_buildingeasting"): Xrm.NumberControl;
    getControl(controlName: "bsr_buildingnorthing"): Xrm.NumberControl;
    getControl(controlName: "bsr_buildingregcompliance"): Xrm.StringControl;
    getControl(controlName: "bsr_buildingregistrationnumber"): Xrm.StringControl;
    getControl(controlName: "bsr_buildoverwithin3mofcentrelineflow"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_changecontrollog"): Xrm.StringControl;
    getControl(controlName: "bsr_changecontrolplan"): Xrm.StringControl;
    getControl(controlName: "bsr_changeofusedescription"): Xrm.StringControl;
    getControl(controlName: "bsr_competencedeclaration"): Xrm.StringControl;
    getControl(controlName: "bsr_completeddate"): Xrm.DateControl;
    getControl(controlName: "bsr_constructioncontrolplan"): Xrm.StringControl;
    getControl(controlName: "bsr_currentheight"): Xrm.NumberControl;
    getControl(controlName: "bsr_currentnonresidentialunits"): Xrm.NumberControl;
    getControl(controlName: "bsr_currentnumberofresidentialunits"): Xrm.NumberControl;
    getControl(controlName: "bsr_currentnumberstoreys"): Xrm.NumberControl;
    getControl(controlName: "bsr_currentprimaryuse"): Xrm.MultiSelectOptionSetControl<bsr_primaryusechoice>;
    getControl(controlName: "bsr_currentstoreyuse"): Xrm.StringControl;
    getControl(controlName: "bsr_existingbuildingworkid"): Xrm.LookupControl<"bsr_bcworkcategory">;
    getControl(controlName: "bsr_existtypeworkproposal"): Xrm.MultiSelectOptionSetControl<bsr_existingusetypeofproposedworkchoic>;
    getControl(controlName: "bsr_firecompliancedoc"): Xrm.StringControl;
    getControl(controlName: "bsr_fireemergencyfiles"): Xrm.StringControl;
    getControl(controlName: "bsr_height"): Xrm.NumberControl;
    getControl(controlName: "bsr_hrbworkid"): Xrm.LookupControl<"bsr_bcworkcategory">;
    getControl(controlName: "bsr_ischangeofuse"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_iscompletedworks"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_localenactment"): Xrm.StringControl;
    getControl(controlName: "bsr_morplan"): Xrm.StringControl;
    getControl(controlName: "bsr_name"): Xrm.StringControl;
    getControl(controlName: "bsr_newdrainorsewer"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_newdrainorsewerlocation"): Xrm.StringControl;
    getControl(controlName: "bsr_nonhrb"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_numbernonresidentialunits"): Xrm.NumberControl;
    getControl(controlName: "bsr_numberresidentialunits"): Xrm.NumberControl;
    getControl(controlName: "bsr_numberstoreys"): Xrm.NumberControl;
    getControl(controlName: "bsr_partialcompletion"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "bsr_partialcompletionstrategy"): Xrm.StringControl;
    getControl(controlName: "bsr_partialoccupationplan"): Xrm.StringControl;
    getControl(controlName: "bsr_pgo"): Xrm.StringControl;
    getControl(controlName: "bsr_pgoreferencenumber"): Xrm.StringControl;
    getControl(controlName: "bsr_plannedbuildtime"): Xrm.NumberControl;
    getControl(controlName: "bsr_planningreferencenumber"): Xrm.StringControl;
    getControl(controlName: "bsr_primaryuse"): Xrm.MultiSelectOptionSetControl<bsr_primaryusechoice>;
    getControl(controlName: "bsr_remainingwork"): Xrm.StringControl;
    getControl(controlName: "bsr_sitelocationplan"): Xrm.StringControl;
    getControl(controlName: "bsr_sitesharedservices"): Xrm.OptionSetControl<bsr_sitesharedserviceschoice>;
    getControl(controlName: "bsr_sitesharedservicesdetails"): Xrm.StringControl;
    getControl(controlName: "bsr_sitesharedservicesurl"): Xrm.StringControl;
    getControl(controlName: "bsr_storeyuse"): Xrm.StringControl;
    getControl(controlName: "bsr_submissiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_tellusaboutyourdrainageprecautions"): Xrm.StringControl;
    getControl(controlName: "bsr_tellusaboutyourdrainageprecautionsdoc"): Xrm.StringControl;
    getControl(controlName: "bsr_workdescription"): Xrm.StringControl;
    getControl(controlName: "header_bsr_buildingdetailsstatus"): Xrm.OptionSetControl<bsr_statusofthebuildingdetailsrecord>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
