declare namespace Form.bsr_buildingcontrollifecycle.Main {
  namespace Information {
    namespace Tabs {
      interface bsr_referrals extends Xrm.SectionCollectionBase {
        get(name: "tab_build_section_8"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_assessment extends Xrm.SectionCollectionBase {
        get(name: "bsr_assessment_requirement"): Xrm.PageSection;
        get(name: "section_approval"): Xrm.PageSection;
        get(name: "section_assessment_timeline"): Xrm.PageSection;
        get(name: "section_information"): Xrm.PageSection;
        get(name: "section_mandatory_timeline"): Xrm.PageSection;
        get(name: "section_phase"): Xrm.PageSection;
        get(name: "section_regulatory"): Xrm.PageSection;
        get(name: "section_rejection "): Xrm.PageSection;
        get(name: "section_requirements"): Xrm.PageSection;
        get(name: "section_time_extension"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_consultation extends Xrm.SectionCollectionBase {
        get(name: "section_fire"): Xrm.PageSection;
        get(name: "section_sewerage"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_meetings extends Xrm.SectionCollectionBase {
        get(name: "section_assessment_meetings"): Xrm.PageSection;
        get(name: "tab_5_section_8"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_notices extends Xrm.SectionCollectionBase {
        get(name: "tab_build_section_7"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_validation extends Xrm.SectionCollectionBase {
        get(name: "AssessmentValidationChecks"): Xrm.PageSection;
        get(name: "buildvalidationchecks"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "bsr_agreedextensionperiod"): Xrm.NumberAttribute;
      get(name: "bsr_allbuildinspectionscomplete"): Xrm.OptionSetAttribute<bsr_allbuildinspectionscomplete>;
      get(name: "bsr_allrequirementsassessed"): Xrm.OptionSetAttribute<bsr_allrequirementsassessed>;
      get(name: "bsr_allrequirementssubmitted"): Xrm.OptionSetAttribute<bsr_allrequirementssubmitted>;
      get(name: "bsr_appassesscomplete"): Xrm.OptionSetAttribute<bsr_appassesscomplete>;
      get(name: "bsr_appassessdatecomplete"): Xrm.DateAttribute;
      get(name: "bsr_approvaldecisiondate"): Xrm.DateAttribute;
      get(name: "bsr_approvaldecisionissueddate"): Xrm.DateAttribute;
      get(name: "bsr_approvaldocument"): Xrm.Attribute<string>;
      get(name: "bsr_approvalemail"): Xrm.Attribute<string>;
      get(name: "bsr_approvalrequirementsdecisiondate"): Xrm.DateAttribute;
      get(name: "bsr_approvalrequirementsdecisionissueddate"): Xrm.DateAttribute;
      get(name: "bsr_approvalrequirementsdocument"): Xrm.Attribute<string>;
      get(name: "bsr_approvalrequirementsemail"): Xrm.Attribute<string>;
      get(name: "bsr_approvalrequirementsinformation"): Xrm.Attribute<string>;
      get(name: "bsr_assessmentofrequirements"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_assessmentofrequirementsoutcome"): Xrm.OptionSetAttribute<bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome>;
      get(name: "bsr_assessrecordsdatefinalised"): Xrm.DateAttribute;
      get(name: "bsr_assesssuccesscriteria"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_bcaaapplication"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
      get(name: "bsr_bcaaapproval"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_bcaaapprovalrequirements"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_bcaarejection"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_bclrcaseofficer"): Xrm.LookupAttribute<"systemuser">;
      get(name: "bsr_bclreference"): Xrm.Attribute<string>;
      get(name: "bsr_bsr_fireereceipt"): Xrm.OptionSetAttribute<bsr_receiptofconsultation>;
      get(name: "bsr_bsr_seweragereceipt"): Xrm.OptionSetAttribute<bsr_receiptofconsultation>;
      get(name: "bsr_buildenddate"): Xrm.DateAttribute;
      get(name: "bsr_buildingcontrollifecyclestatus"): Xrm.OptionSetAttribute<bsr_buildingcontrollifecyclestatus>;
      get(name: "bsr_buildingdetails"): Xrm.LookupAttribute<"bsr_buildingdetails">;
      get(name: "bsr_buildinspectionscompletedate"): Xrm.DateAttribute;
      get(name: "bsr_ccfirereceipt"): Xrm.OptionSetAttribute<bsr_ccfirereceiptchoice>;
      get(name: "bsr_ccseweragereceipt"): Xrm.OptionSetAttribute<bsr_ccfirereceiptchoice>;
      get(name: "bsr_changecontrol"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_completioncertappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
      get(name: "bsr_dutyholderagreement"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_dutyholderagreementemail"): Xrm.Attribute<string>;
      get(name: "bsr_finaliseassessrecords"): Xrm.OptionSetAttribute<bsr_finaliseassessrecords>;
      get(name: "bsr_fireconsultationurl"): Xrm.Attribute<string>;
      get(name: "bsr_fireconsultee"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_fireconsulteereceiveddate"): Xrm.DateAttribute;
      get(name: "bsr_fireconsulteerequestdate"): Xrm.DateAttribute;
      get(name: "bsr_fireextensionagreed"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_fireextensionagreement"): Xrm.Attribute<string>;
      get(name: "bsr_fireextensionrequest"): Xrm.Attribute<string>;
      get(name: "bsr_fireextensionrequired"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_firerequestemailurl"): Xrm.Attribute<string>;
      get(name: "bsr_isbuildcomplete"): Xrm.OptionSetAttribute<bsr_isbuildcomplete>;
      get(name: "bsr_lifecyclecancellationreason"): Xrm.OptionSetAttribute<bsr_lifecyclecancellationreason>;
      get(name: "bsr_lifecyclecompletionreason"): Xrm.OptionSetAttribute<bsr_lifecyclecompletionreason>;
      get(name: "bsr_lifecyclephase"): Xrm.OptionSetAttribute<bsr_lifecyclephase>;
      get(name: "bsr_mandatorytimelinefailuredate"): Xrm.DateAttribute;
      get(name: "bsr_name"): Xrm.Attribute<string>;
      get(name: "bsr_numberofrequirements"): Xrm.NumberAttribute;
      get(name: "bsr_outcomedecisionissueddate"): Xrm.DateAttribute;
      get(name: "bsr_outcomedocument"): Xrm.Attribute<string>;
      get(name: "bsr_outcomeemail"): Xrm.Attribute<string>;
      get(name: "bsr_outcomeinformation"): Xrm.Attribute<string>;
      get(name: "bsr_outstandingissueschecked"): Xrm.OptionSetAttribute<bsr_outstandingissueschecked>;
      get(name: "bsr_outstandingissuesdatecompleted"): Xrm.DateAttribute;
      get(name: "bsr_reasonrequired"): Xrm.Attribute<string>;
      get(name: "bsr_reglead"): Xrm.LookupAttribute<"systemuser">;
      get(name: "bsr_regtaskscheduledatecreated"): Xrm.DateAttribute;
      get(name: "bsr_regulatorytaskschedulecreated"): Xrm.OptionSetAttribute<bsr_regulatorytaskschedulecreated>;
      get(name: "bsr_rejectiondecisiondate"): Xrm.DateAttribute;
      get(name: "bsr_rejectiondecisionissueddate"): Xrm.DateAttribute;
      get(name: "bsr_rejectiondocument"): Xrm.Attribute<string>;
      get(name: "bsr_rejectionemail"): Xrm.Attribute<string>;
      get(name: "bsr_rejectionreasons"): Xrm.Attribute<string>;
      get(name: "bsr_requirementsubmissiondate"): Xrm.DateAttribute;
      get(name: "bsr_sewerageconsultationreceiveddate"): Xrm.DateAttribute;
      get(name: "bsr_sewerageconsultationrequestdate"): Xrm.DateAttribute;
      get(name: "bsr_sewerageconsultationurl"): Xrm.Attribute<string>;
      get(name: "bsr_sewerageextensionagreed"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_sewerageextensionagreement"): Xrm.Attribute<string>;
      get(name: "bsr_sewerageextensionrequired"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_seweragerequestemailurl"): Xrm.Attribute<string>;
      get(name: "bsr_seweragerxtensionrequest"): Xrm.Attribute<string>;
      get(name: "bsr_sewerageundertaker"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_statfireconsultfailuredate"): Xrm.DateAttribute;
      get(name: "bsr_statfireconsultsuccess"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_statsewerconsultfailuredate"): Xrm.DateAttribute;
      get(name: "bsr_statsewerconsultsuccess"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_supportingbcl"): Xrm.LookupAttribute<"bsr_buildingcontrollifecycle">;
      get(name: "bsr_timeextensionemail"): Xrm.Attribute<string>;
      get(name: "bsr_timerequirement"): Xrm.NumberAttribute;
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_otherregulatorreferral">;
      get(name: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_buildmeetings">;
      get(name: "Subgrid_new_6"): Xrm.SubGridControl<"bsr_assessmentmeeting">;
      get(name: "Subgrid_new_7"): Xrm.SubGridControl<"bsr_notices">;
      get(name: "bsr_agreedextensionperiod"): Xrm.NumberControl;
      get(name: "bsr_allbuildinspectionscomplete"): Xrm.OptionSetControl<bsr_allbuildinspectionscomplete>;
      get(name: "bsr_allrequirementsassessed"): Xrm.OptionSetControl<bsr_allrequirementsassessed>;
      get(name: "bsr_allrequirementssubmitted"): Xrm.OptionSetControl<bsr_allrequirementssubmitted>;
      get(name: "bsr_appassesscomplete"): Xrm.OptionSetControl<bsr_appassesscomplete>;
      get(name: "bsr_appassessdatecomplete"): Xrm.DateControl;
      get(name: "bsr_approvaldecisiondate"): Xrm.DateControl;
      get(name: "bsr_approvaldecisionissueddate"): Xrm.DateControl;
      get(name: "bsr_approvaldocument"): Xrm.StringControl;
      get(name: "bsr_approvalemail"): Xrm.StringControl;
      get(name: "bsr_approvalrequirementsdecisiondate"): Xrm.DateControl;
      get(name: "bsr_approvalrequirementsdecisionissueddate"): Xrm.DateControl;
      get(name: "bsr_approvalrequirementsdocument"): Xrm.StringControl;
      get(name: "bsr_approvalrequirementsemail"): Xrm.StringControl;
      get(name: "bsr_approvalrequirementsinformation"): Xrm.StringControl;
      get(name: "bsr_assessmentofrequirements"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_assessmentofrequirementsoutcome"): Xrm.OptionSetControl<bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome>;
      get(name: "bsr_assessrecordsdatefinalised"): Xrm.DateControl;
      get(name: "bsr_assesssuccesscriteria"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_bcaaapplication"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_bcaaapproval"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_bcaaapprovalrequirements"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_bcaarejection"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_bclrcaseofficer"): Xrm.LookupControl<"systemuser">;
      get(name: "bsr_bclreference"): Xrm.StringControl;
      get(name: "bsr_bsr_fireereceipt"): Xrm.OptionSetControl<bsr_receiptofconsultation>;
      get(name: "bsr_bsr_seweragereceipt"): Xrm.OptionSetControl<bsr_receiptofconsultation>;
      get(name: "bsr_buildenddate"): Xrm.DateControl;
      get(name: "bsr_buildingdetails"): Xrm.LookupControl<"bsr_buildingdetails">;
      get(name: "bsr_buildinspectionscompletedate"): Xrm.DateControl;
      get(name: "bsr_ccfirereceipt"): Xrm.OptionSetControl<bsr_ccfirereceiptchoice>;
      get(name: "bsr_ccseweragereceipt"): Xrm.OptionSetControl<bsr_ccfirereceiptchoice>;
      get(name: "bsr_changecontrol"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_completioncertappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_dutyholderagreement"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_dutyholderagreementemail"): Xrm.StringControl;
      get(name: "bsr_finaliseassessrecords"): Xrm.OptionSetControl<bsr_finaliseassessrecords>;
      get(name: "bsr_fireconsultationurl"): Xrm.StringControl;
      get(name: "bsr_fireconsultee"): Xrm.LookupControl<"contact">;
      get(name: "bsr_fireconsulteereceiveddate"): Xrm.DateControl;
      get(name: "bsr_fireconsulteerequestdate"): Xrm.DateControl;
      get(name: "bsr_fireconsulteetimer"): Xrm.BaseControl;
      get(name: "bsr_fireextensionagreed"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_fireextensionagreement"): Xrm.StringControl;
      get(name: "bsr_fireextensionrequest"): Xrm.StringControl;
      get(name: "bsr_fireextensionrequired"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_firerequestemailurl"): Xrm.StringControl;
      get(name: "bsr_isbuildcomplete"): Xrm.OptionSetControl<bsr_isbuildcomplete>;
      get(name: "bsr_lifecyclecancellationreason"): Xrm.OptionSetControl<bsr_lifecyclecancellationreason>;
      get(name: "bsr_lifecyclecompletionreason"): Xrm.OptionSetControl<bsr_lifecyclecompletionreason>;
      get(name: "bsr_mandatorytimelinefailuredate"): Xrm.DateControl;
      get(name: "bsr_mandatorytimer"): Xrm.BaseControl;
      get(name: "bsr_name"): Xrm.StringControl;
      get(name: "bsr_numberofrequirements"): Xrm.NumberControl;
      get(name: "bsr_outcomedecisionissueddate"): Xrm.DateControl;
      get(name: "bsr_outcomedocument"): Xrm.StringControl;
      get(name: "bsr_outcomeemail"): Xrm.StringControl;
      get(name: "bsr_outcomeinformation"): Xrm.StringControl;
      get(name: "bsr_outstandingissueschecked"): Xrm.OptionSetControl<bsr_outstandingissueschecked>;
      get(name: "bsr_outstandingissuesdatecompleted"): Xrm.DateControl;
      get(name: "bsr_reasonrequired"): Xrm.StringControl;
      get(name: "bsr_reglead"): Xrm.LookupControl<"systemuser">;
      get(name: "bsr_regtaskscheduledatecreated"): Xrm.DateControl;
      get(name: "bsr_regulatorytaskschedulecreated"): Xrm.OptionSetControl<bsr_regulatorytaskschedulecreated>;
      get(name: "bsr_rejectiondecisiondate"): Xrm.DateControl;
      get(name: "bsr_rejectiondecisionissueddate"): Xrm.DateControl;
      get(name: "bsr_rejectiondocument"): Xrm.StringControl;
      get(name: "bsr_rejectionemail"): Xrm.StringControl;
      get(name: "bsr_rejectionreasons"): Xrm.StringControl;
      get(name: "bsr_requirementsubmissiondate"): Xrm.DateControl;
      get(name: "bsr_sewerageconsultationreceiveddate"): Xrm.DateControl;
      get(name: "bsr_sewerageconsultationrequestdate"): Xrm.DateControl;
      get(name: "bsr_sewerageconsultationurl"): Xrm.StringControl;
      get(name: "bsr_sewerageconsulttimer"): Xrm.BaseControl;
      get(name: "bsr_sewerageextensionagreed"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_sewerageextensionagreement"): Xrm.StringControl;
      get(name: "bsr_sewerageextensionrequired"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_seweragerequestemailurl"): Xrm.StringControl;
      get(name: "bsr_seweragerxtensionrequest"): Xrm.StringControl;
      get(name: "bsr_sewerageundertaker"): Xrm.LookupControl<"contact">;
      get(name: "bsr_statfireconsultfailuredate"): Xrm.DateControl;
      get(name: "bsr_statfireconsultsuccess"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_statsewerconsultfailuredate"): Xrm.DateControl;
      get(name: "bsr_statsewerconsultsuccess"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_supportingbcl"): Xrm.LookupControl<"bsr_buildingcontrollifecycle">;
      get(name: "bsr_timeextensionemail"): Xrm.StringControl;
      get(name: "bsr_timerequirement"): Xrm.NumberControl;
      get(name: "createdon"): Xrm.DateControl;
      get(name: "header_bsr_buildingcontrollifecyclestatus"): Xrm.OptionSetControl<bsr_buildingcontrollifecyclestatus>;
      get(name: "header_bsr_lifecyclephase"): Xrm.OptionSetControl<bsr_lifecyclephase>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_process_bsr_allrequirementsassessed"): Xrm.OptionSetControl<bsr_allrequirementsassessed> | null;
      get(name: "header_process_bsr_allrequirementssubmitted"): Xrm.OptionSetControl<bsr_allrequirementssubmitted> | null;
      get(name: "header_process_bsr_appassesscomplete"): Xrm.OptionSetControl<bsr_appassesscomplete> | null;
      get(name: "header_process_bsr_appassessdatecomplete"): Xrm.DateControl | null;
      get(name: "header_process_bsr_approvaldecisionissueddate"): Xrm.DateControl | null;
      get(name: "header_process_bsr_approvalrequirementsdecisionissueddate"): Xrm.DateControl | null;
      get(name: "header_process_bsr_assessrecordsdatefinalised"): Xrm.DateControl | null;
      get(name: "header_process_bsr_bcaaapplication"): Xrm.LookupControl<"bsr_buildingcontrolapplication"> | null;
      get(name: "header_process_bsr_bcaaapproval"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_bsr_bcaaapprovalrequirements"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_bsr_bcaarejection"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_bsr_buildingdetails"): Xrm.LookupControl<"bsr_buildingdetails"> | null;
      get(name: "header_process_bsr_buildinspectionscompletedate"): Xrm.DateControl | null;
      get(name: "header_process_bsr_buildinspectionscompletedate_1"): Xrm.DateControl | null;
      get(name: "header_process_bsr_finaliseassessrecords"): Xrm.OptionSetControl<bsr_finaliseassessrecords> | null;
      get(name: "header_process_bsr_isbuildcomplete"): Xrm.OptionSetControl<bsr_isbuildcomplete> | null;
      get(name: "header_process_bsr_isbuildcomplete_1"): Xrm.OptionSetControl<bsr_isbuildcomplete> | null;
      get(name: "header_process_bsr_outstandingissueschecked"): Xrm.OptionSetControl<bsr_outstandingissueschecked> | null;
      get(name: "header_process_bsr_outstandingissuesdatecompleted"): Xrm.DateControl | null;
      get(name: "header_process_bsr_reglead"): Xrm.LookupControl<"systemuser"> | null;
      get(name: "header_process_bsr_regtaskscheduledatecreated"): Xrm.DateControl | null;
      get(name: "header_process_bsr_regulatorytaskschedulecreated"): Xrm.OptionSetControl<bsr_regulatorytaskschedulecreated> | null;
      get(name: "header_process_bsr_rejectiondecisionissueddate"): Xrm.DateControl | null;
      get(name: "header_process_createdon"): Xrm.DateControl | null;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "bsr_referrals"): Xrm.PageTab<Tabs.bsr_referrals>;
      get(name: "tab_assessment"): Xrm.PageTab<Tabs.tab_assessment>;
      get(name: "tab_consultation"): Xrm.PageTab<Tabs.tab_consultation>;
      get(name: "tab_meetings"): Xrm.PageTab<Tabs.tab_meetings>;
      get(name: "tab_notices"): Xrm.PageTab<Tabs.tab_notices>;
      get(name: "tab_validation"): Xrm.PageTab<Tabs.tab_validation>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "bsr_agreedextensionperiod"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_allbuildinspectionscomplete"): Xrm.OptionSetAttribute<bsr_allbuildinspectionscomplete>;
    getAttribute(attributeName: "bsr_allrequirementsassessed"): Xrm.OptionSetAttribute<bsr_allrequirementsassessed>;
    getAttribute(attributeName: "bsr_allrequirementssubmitted"): Xrm.OptionSetAttribute<bsr_allrequirementssubmitted>;
    getAttribute(attributeName: "bsr_appassesscomplete"): Xrm.OptionSetAttribute<bsr_appassesscomplete>;
    getAttribute(attributeName: "bsr_appassessdatecomplete"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_approvaldecisiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_approvaldecisionissueddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_approvaldocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_approvalemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_approvalrequirementsdecisiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_approvalrequirementsdecisionissueddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_approvalrequirementsdocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_approvalrequirementsemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_approvalrequirementsinformation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_assessmentofrequirements"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_assessmentofrequirementsoutcome"): Xrm.OptionSetAttribute<bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome>;
    getAttribute(attributeName: "bsr_assessrecordsdatefinalised"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_assesssuccesscriteria"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_bcaaapplication"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
    getAttribute(attributeName: "bsr_bcaaapproval"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_bcaaapprovalrequirements"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_bcaarejection"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_bclrcaseofficer"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "bsr_bclreference"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_bsr_fireereceipt"): Xrm.OptionSetAttribute<bsr_receiptofconsultation>;
    getAttribute(attributeName: "bsr_bsr_seweragereceipt"): Xrm.OptionSetAttribute<bsr_receiptofconsultation>;
    getAttribute(attributeName: "bsr_buildenddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_buildingcontrollifecyclestatus"): Xrm.OptionSetAttribute<bsr_buildingcontrollifecyclestatus>;
    getAttribute(attributeName: "bsr_buildingdetails"): Xrm.LookupAttribute<"bsr_buildingdetails">;
    getAttribute(attributeName: "bsr_buildinspectionscompletedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_ccfirereceipt"): Xrm.OptionSetAttribute<bsr_ccfirereceiptchoice>;
    getAttribute(attributeName: "bsr_ccseweragereceipt"): Xrm.OptionSetAttribute<bsr_ccfirereceiptchoice>;
    getAttribute(attributeName: "bsr_changecontrol"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_completioncertappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
    getAttribute(attributeName: "bsr_dutyholderagreement"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_dutyholderagreementemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_finaliseassessrecords"): Xrm.OptionSetAttribute<bsr_finaliseassessrecords>;
    getAttribute(attributeName: "bsr_fireconsultationurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_fireconsultee"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_fireconsulteereceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_fireconsulteerequestdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_fireextensionagreed"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_fireextensionagreement"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_fireextensionrequest"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_fireextensionrequired"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_firerequestemailurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_isbuildcomplete"): Xrm.OptionSetAttribute<bsr_isbuildcomplete>;
    getAttribute(attributeName: "bsr_lifecyclecancellationreason"): Xrm.OptionSetAttribute<bsr_lifecyclecancellationreason>;
    getAttribute(attributeName: "bsr_lifecyclecompletionreason"): Xrm.OptionSetAttribute<bsr_lifecyclecompletionreason>;
    getAttribute(attributeName: "bsr_lifecyclephase"): Xrm.OptionSetAttribute<bsr_lifecyclephase>;
    getAttribute(attributeName: "bsr_mandatorytimelinefailuredate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_numberofrequirements"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_outcomedecisionissueddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_outcomedocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_outcomeemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_outcomeinformation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_outstandingissueschecked"): Xrm.OptionSetAttribute<bsr_outstandingissueschecked>;
    getAttribute(attributeName: "bsr_outstandingissuesdatecompleted"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_reasonrequired"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_reglead"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "bsr_regtaskscheduledatecreated"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_regulatorytaskschedulecreated"): Xrm.OptionSetAttribute<bsr_regulatorytaskschedulecreated>;
    getAttribute(attributeName: "bsr_rejectiondecisiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_rejectiondecisionissueddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_rejectiondocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_rejectionemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_rejectionreasons"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_requirementsubmissiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_sewerageconsultationreceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_sewerageconsultationrequestdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_sewerageconsultationurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sewerageextensionagreed"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_sewerageextensionagreement"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sewerageextensionrequired"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_seweragerequestemailurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_seweragerxtensionrequest"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sewerageundertaker"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_statfireconsultfailuredate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_statfireconsultsuccess"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_statsewerconsultfailuredate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_statsewerconsultsuccess"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_supportingbcl"): Xrm.LookupAttribute<"bsr_buildingcontrollifecycle">;
    getAttribute(attributeName: "bsr_timeextensionemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_timerequirement"): Xrm.NumberAttribute;
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_otherregulatorreferral">;
    getControl(controlName: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_buildmeetings">;
    getControl(controlName: "Subgrid_new_6"): Xrm.SubGridControl<"bsr_assessmentmeeting">;
    getControl(controlName: "Subgrid_new_7"): Xrm.SubGridControl<"bsr_notices">;
    getControl(controlName: "bsr_agreedextensionperiod"): Xrm.NumberControl;
    getControl(controlName: "bsr_allbuildinspectionscomplete"): Xrm.OptionSetControl<bsr_allbuildinspectionscomplete>;
    getControl(controlName: "bsr_allrequirementsassessed"): Xrm.OptionSetControl<bsr_allrequirementsassessed>;
    getControl(controlName: "bsr_allrequirementssubmitted"): Xrm.OptionSetControl<bsr_allrequirementssubmitted>;
    getControl(controlName: "bsr_appassesscomplete"): Xrm.OptionSetControl<bsr_appassesscomplete>;
    getControl(controlName: "bsr_appassessdatecomplete"): Xrm.DateControl;
    getControl(controlName: "bsr_approvaldecisiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_approvaldecisionissueddate"): Xrm.DateControl;
    getControl(controlName: "bsr_approvaldocument"): Xrm.StringControl;
    getControl(controlName: "bsr_approvalemail"): Xrm.StringControl;
    getControl(controlName: "bsr_approvalrequirementsdecisiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_approvalrequirementsdecisionissueddate"): Xrm.DateControl;
    getControl(controlName: "bsr_approvalrequirementsdocument"): Xrm.StringControl;
    getControl(controlName: "bsr_approvalrequirementsemail"): Xrm.StringControl;
    getControl(controlName: "bsr_approvalrequirementsinformation"): Xrm.StringControl;
    getControl(controlName: "bsr_assessmentofrequirements"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_assessmentofrequirementsoutcome"): Xrm.OptionSetControl<bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome>;
    getControl(controlName: "bsr_assessrecordsdatefinalised"): Xrm.DateControl;
    getControl(controlName: "bsr_assesssuccesscriteria"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_bcaaapplication"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_bcaaapproval"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_bcaaapprovalrequirements"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_bcaarejection"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_bclrcaseofficer"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "bsr_bclreference"): Xrm.StringControl;
    getControl(controlName: "bsr_bsr_fireereceipt"): Xrm.OptionSetControl<bsr_receiptofconsultation>;
    getControl(controlName: "bsr_bsr_seweragereceipt"): Xrm.OptionSetControl<bsr_receiptofconsultation>;
    getControl(controlName: "bsr_buildenddate"): Xrm.DateControl;
    getControl(controlName: "bsr_buildingdetails"): Xrm.LookupControl<"bsr_buildingdetails">;
    getControl(controlName: "bsr_buildinspectionscompletedate"): Xrm.DateControl;
    getControl(controlName: "bsr_ccfirereceipt"): Xrm.OptionSetControl<bsr_ccfirereceiptchoice>;
    getControl(controlName: "bsr_ccseweragereceipt"): Xrm.OptionSetControl<bsr_ccfirereceiptchoice>;
    getControl(controlName: "bsr_changecontrol"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_completioncertappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_dutyholderagreement"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_dutyholderagreementemail"): Xrm.StringControl;
    getControl(controlName: "bsr_finaliseassessrecords"): Xrm.OptionSetControl<bsr_finaliseassessrecords>;
    getControl(controlName: "bsr_fireconsultationurl"): Xrm.StringControl;
    getControl(controlName: "bsr_fireconsultee"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_fireconsulteereceiveddate"): Xrm.DateControl;
    getControl(controlName: "bsr_fireconsulteerequestdate"): Xrm.DateControl;
    getControl(controlName: "bsr_fireconsulteetimer"): Xrm.BaseControl;
    getControl(controlName: "bsr_fireextensionagreed"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_fireextensionagreement"): Xrm.StringControl;
    getControl(controlName: "bsr_fireextensionrequest"): Xrm.StringControl;
    getControl(controlName: "bsr_fireextensionrequired"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_firerequestemailurl"): Xrm.StringControl;
    getControl(controlName: "bsr_isbuildcomplete"): Xrm.OptionSetControl<bsr_isbuildcomplete>;
    getControl(controlName: "bsr_lifecyclecancellationreason"): Xrm.OptionSetControl<bsr_lifecyclecancellationreason>;
    getControl(controlName: "bsr_lifecyclecompletionreason"): Xrm.OptionSetControl<bsr_lifecyclecompletionreason>;
    getControl(controlName: "bsr_mandatorytimelinefailuredate"): Xrm.DateControl;
    getControl(controlName: "bsr_mandatorytimer"): Xrm.BaseControl;
    getControl(controlName: "bsr_name"): Xrm.StringControl;
    getControl(controlName: "bsr_numberofrequirements"): Xrm.NumberControl;
    getControl(controlName: "bsr_outcomedecisionissueddate"): Xrm.DateControl;
    getControl(controlName: "bsr_outcomedocument"): Xrm.StringControl;
    getControl(controlName: "bsr_outcomeemail"): Xrm.StringControl;
    getControl(controlName: "bsr_outcomeinformation"): Xrm.StringControl;
    getControl(controlName: "bsr_outstandingissueschecked"): Xrm.OptionSetControl<bsr_outstandingissueschecked>;
    getControl(controlName: "bsr_outstandingissuesdatecompleted"): Xrm.DateControl;
    getControl(controlName: "bsr_reasonrequired"): Xrm.StringControl;
    getControl(controlName: "bsr_reglead"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "bsr_regtaskscheduledatecreated"): Xrm.DateControl;
    getControl(controlName: "bsr_regulatorytaskschedulecreated"): Xrm.OptionSetControl<bsr_regulatorytaskschedulecreated>;
    getControl(controlName: "bsr_rejectiondecisiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_rejectiondecisionissueddate"): Xrm.DateControl;
    getControl(controlName: "bsr_rejectiondocument"): Xrm.StringControl;
    getControl(controlName: "bsr_rejectionemail"): Xrm.StringControl;
    getControl(controlName: "bsr_rejectionreasons"): Xrm.StringControl;
    getControl(controlName: "bsr_requirementsubmissiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_sewerageconsultationreceiveddate"): Xrm.DateControl;
    getControl(controlName: "bsr_sewerageconsultationrequestdate"): Xrm.DateControl;
    getControl(controlName: "bsr_sewerageconsultationurl"): Xrm.StringControl;
    getControl(controlName: "bsr_sewerageconsulttimer"): Xrm.BaseControl;
    getControl(controlName: "bsr_sewerageextensionagreed"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_sewerageextensionagreement"): Xrm.StringControl;
    getControl(controlName: "bsr_sewerageextensionrequired"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_seweragerequestemailurl"): Xrm.StringControl;
    getControl(controlName: "bsr_seweragerxtensionrequest"): Xrm.StringControl;
    getControl(controlName: "bsr_sewerageundertaker"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_statfireconsultfailuredate"): Xrm.DateControl;
    getControl(controlName: "bsr_statfireconsultsuccess"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_statsewerconsultfailuredate"): Xrm.DateControl;
    getControl(controlName: "bsr_statsewerconsultsuccess"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_supportingbcl"): Xrm.LookupControl<"bsr_buildingcontrollifecycle">;
    getControl(controlName: "bsr_timeextensionemail"): Xrm.StringControl;
    getControl(controlName: "bsr_timerequirement"): Xrm.NumberControl;
    getControl(controlName: "createdon"): Xrm.DateControl;
    getControl(controlName: "header_bsr_buildingcontrollifecyclestatus"): Xrm.OptionSetControl<bsr_buildingcontrollifecyclestatus>;
    getControl(controlName: "header_bsr_lifecyclephase"): Xrm.OptionSetControl<bsr_lifecyclephase>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_process_bsr_allrequirementsassessed"): Xrm.OptionSetControl<bsr_allrequirementsassessed> | null;
    getControl(controlName: "header_process_bsr_allrequirementssubmitted"): Xrm.OptionSetControl<bsr_allrequirementssubmitted> | null;
    getControl(controlName: "header_process_bsr_appassesscomplete"): Xrm.OptionSetControl<bsr_appassesscomplete> | null;
    getControl(controlName: "header_process_bsr_appassessdatecomplete"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_approvaldecisionissueddate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_approvalrequirementsdecisionissueddate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_assessrecordsdatefinalised"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_bcaaapplication"): Xrm.LookupControl<"bsr_buildingcontrolapplication"> | null;
    getControl(controlName: "header_process_bsr_bcaaapproval"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_bsr_bcaaapprovalrequirements"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_bsr_bcaarejection"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_bsr_buildingdetails"): Xrm.LookupControl<"bsr_buildingdetails"> | null;
    getControl(controlName: "header_process_bsr_buildinspectionscompletedate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_buildinspectionscompletedate_1"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_finaliseassessrecords"): Xrm.OptionSetControl<bsr_finaliseassessrecords> | null;
    getControl(controlName: "header_process_bsr_isbuildcomplete"): Xrm.OptionSetControl<bsr_isbuildcomplete> | null;
    getControl(controlName: "header_process_bsr_isbuildcomplete_1"): Xrm.OptionSetControl<bsr_isbuildcomplete> | null;
    getControl(controlName: "header_process_bsr_outstandingissueschecked"): Xrm.OptionSetControl<bsr_outstandingissueschecked> | null;
    getControl(controlName: "header_process_bsr_outstandingissuesdatecompleted"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_reglead"): Xrm.LookupControl<"systemuser"> | null;
    getControl(controlName: "header_process_bsr_regtaskscheduledatecreated"): Xrm.DateControl | null;
    getControl(controlName: "header_process_bsr_regulatorytaskschedulecreated"): Xrm.OptionSetControl<bsr_regulatorytaskschedulecreated> | null;
    getControl(controlName: "header_process_bsr_rejectiondecisionissueddate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_createdon"): Xrm.DateControl | null;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
