declare namespace Form.bsr_buildingprofessionapplication.Main {
  namespace Information {
    namespace Tabs {
      interface BIClassInfoTab extends Xrm.SectionCollectionBase {
        get(name: "BIRegistrationActivities"): Xrm.PageSection;
        get(name: "BIRegistrationClass"): Xrm.PageSection;
        get(name: "BIRegistrationCountries"): Xrm.PageSection;
        get(name: "_section_168"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface EmploymentDetails extends Xrm.SectionCollectionBase {
        get(name: "EmploymentDetails"): Xrm.PageSection;
        get(name: "tab_6_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Memberships extends Xrm.SectionCollectionBase {
        get(name: "ProfessionalMemberships"): Xrm.PageSection;
        get(name: "tab_5_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface competency extends Xrm.SectionCollectionBase {
        get(name: "BIIndependentAssessments"): Xrm.PageSection;
        get(name: "indepedentassessmentdata"): Xrm.PageSection;
        get(name: "tab_4_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface rbcainfo extends Xrm.SectionCollectionBase {
        get(name: "businessdetails"): Xrm.PageSection;
        get(name: "rbcainfo_section_5"): Xrm.PageSection;
        get(name: "rbcainfo_section_6"): Xrm.PageSection;
        get(name: "rbcainfo_section_7"): Xrm.PageSection;
        get(name: "rbcainfo_section_8"): Xrm.PageSection;
        get(name: "rbcainfo_section_9"): Xrm.PageSection;
        get(name: "tab_7_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_3 extends Xrm.SectionCollectionBase {
        get(name: "_section_593"): Xrm.PageSection;
        get(name: "payments"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "bsr_applicantid"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "bsr_assessmentcertnumber"): Xrm.Attribute<string>;
      get(name: "bsr_assessmentdate"): Xrm.DateAttribute;
      get(name: "bsr_assessmentorganisationid"): Xrm.LookupAttribute<"account">;
      get(name: "bsr_assessmentstatus"): Xrm.OptionSetAttribute<bsr_assessmentstatus>;
      get(name: "bsr_buildingproappid"): Xrm.Attribute<string>;
      get(name: "bsr_buildingprofessiontypecode"): Xrm.OptionSetAttribute<bsr_buildingprofessiontypecode>;
      get(name: "bsr_cicairregnumber"): Xrm.Attribute<string>;
      get(name: "bsr_countofrbis"): Xrm.Attribute<string>;
      get(name: "bsr_countpreregrbis"): Xrm.Attribute<string>;
      get(name: "bsr_decisioncondition"): Xrm.Attribute<string>;
      get(name: "bsr_decisiondate"): Xrm.DateAttribute;
      get(name: "bsr_decisionreason"): Xrm.Attribute<string>;
      get(name: "bsr_declarationdate"): Xrm.DateAttribute;
      get(name: "bsr_escalationstatus"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_hasindependentassessment"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_holdreviewdate"): Xrm.DateAttribute;
      get(name: "bsr_isantimoneylaundering"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isbusinessservicesoffered"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isbusregisteredasapprovedins"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_iscomplaints"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isconfirmationofcurrentownersdirectors"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isconflictofinterest"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_iscontractormanagement"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isdataprotection"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isenforcementorprosecution"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isequalitydivertyinclusion"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isformalorgstructure"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_ishascriminalconvictions"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_ishealthsafetywellbeing"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isinternalaudit"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isongoinghighriskbuildingprojects"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isoperatingproceduresprovided"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isrbisnamesprovided"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isrecommendedforrejection"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isrecruitmentandstaffdev"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isrelevantchangessincereg"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_issendregulatorydecisionemail"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isstaffconduct"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_issubjecttoinvestigations"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isunregrbisnamesprovided"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_iswhistleblowing"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_name"): Xrm.Attribute<string>;
      get(name: "bsr_onholdreason"): Xrm.LookupAttribute<"bsr_onholdreason">;
      get(name: "bsr_primarycontactposition"): Xrm.Attribute<string>;
      get(name: "bsr_prioritisationcode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_bsr_prioritisationcode>;
      get(name: "bsr_rbcaaccountid"): Xrm.LookupAttribute<"account">;
      get(name: "bsr_rbcadeclaration"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_rbcadeclarationfirstname"): Xrm.Attribute<string>;
      get(name: "bsr_rbcadeclarationlastname"): Xrm.Attribute<string>;
      get(name: "bsr_rbcadeclarationpositioninbusiness"): Xrm.Attribute<string>;
      get(name: "bsr_rbcaprimarycontactid"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_rbcasecondarycontactid"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_recommendedrejectionreason"): Xrm.Attribute<string>;
      get(name: "bsr_registrationcommencementdate"): Xrm.DateAttribute;
      get(name: "bsr_regulatorydecisionstatus"): Xrm.OptionSetAttribute<bsr_regulatorydecisionstatus>;
      get(name: "bsr_reviewdecision"): Xrm.Attribute<string>;
      get(name: "bsr_reviewstatus"): Xrm.OptionSetAttribute<bsr_reviewstatus>;
      get(name: "bsr_secondarycontactposition"): Xrm.Attribute<string>;
      get(name: "bsr_sizoeoforgcode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_bsr_sizoeoforgcode>;
      get(name: "bsr_tellusaboutanyotherrelevantbusinesseswhich"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_typeofbusiness"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statuscode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_statuscode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "BIIndependentAssessments"): Xrm.SubGridControl<"bsr_biindependentassessment">;
      get(name: "BIRegistrationActivities"): Xrm.SubGridControl<"bsr_biregactivity">;
      get(name: "BIRegistrationClass"): Xrm.SubGridControl<"bsr_biregclass">;
      get(name: "BIRegistrationCountries"): Xrm.SubGridControl<"bsr_biregcountry">;
      get(name: "EmploymentDetails"): Xrm.SubGridControl<"bsr_biemploymentdetail">;
      get(name: "ProfessionalMemberships"): Xrm.SubGridControl<"bsr_biprofessionalmembership">;
      get(name: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_registrationregion">;
      get(name: "bsr_applicantid"): Xrm.LookupControl<"account" | "contact">;
      get(name: "bsr_assessmentcertnumber"): Xrm.StringControl;
      get(name: "bsr_assessmentdate"): Xrm.DateControl;
      get(name: "bsr_assessmentorganisationid"): Xrm.LookupControl<"account">;
      get(name: "bsr_assessmentstatus"): Xrm.OptionSetControl<bsr_assessmentstatus>;
      get(name: "bsr_buildingproappid"): Xrm.StringControl;
      get(name: "bsr_buildingprofessiontypecode"): Xrm.OptionSetControl<bsr_buildingprofessiontypecode>;
      get(name: "bsr_cicairregnumber"): Xrm.StringControl;
      get(name: "bsr_countofrbis"): Xrm.StringControl;
      get(name: "bsr_countpreregrbis"): Xrm.StringControl;
      get(name: "bsr_decisioncondition"): Xrm.StringControl;
      get(name: "bsr_decisiondate"): Xrm.DateControl;
      get(name: "bsr_decisionreason"): Xrm.StringControl;
      get(name: "bsr_declarationdate"): Xrm.DateControl;
      get(name: "bsr_escalationstatus"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_hasindependentassessment"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_holdreviewdate"): Xrm.DateControl;
      get(name: "bsr_isantimoneylaundering"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isbusinessservicesoffered"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isbusregisteredasapprovedins"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_iscomplaints"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isconfirmationofcurrentownersdirectors"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isconflictofinterest"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_iscontractormanagement"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isdataprotection"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isenforcementorprosecution"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isequalitydivertyinclusion"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isformalorgstructure"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_ishascriminalconvictions"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_ishealthsafetywellbeing"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isinternalaudit"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isongoinghighriskbuildingprojects"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isoperatingproceduresprovided"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isrbisnamesprovided"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isrecommendedforrejection"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isrecruitmentandstaffdev"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isrelevantchangessincereg"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_issendregulatorydecisionemail"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isstaffconduct"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_issubjecttoinvestigations"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isunregrbisnamesprovided"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_iswhistleblowing"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_name"): Xrm.StringControl;
      get(name: "bsr_onholdreason"): Xrm.LookupControl<"bsr_onholdreason">;
      get(name: "bsr_primarycontactposition"): Xrm.StringControl;
      get(name: "bsr_prioritisationcode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_bsr_prioritisationcode>;
      get(name: "bsr_rbcaaccountid"): Xrm.LookupControl<"account">;
      get(name: "bsr_rbcadeclaration"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_rbcadeclarationfirstname"): Xrm.StringControl;
      get(name: "bsr_rbcadeclarationlastname"): Xrm.StringControl;
      get(name: "bsr_rbcadeclarationpositioninbusiness"): Xrm.StringControl;
      get(name: "bsr_rbcaprimarycontactid"): Xrm.LookupControl<"contact">;
      get(name: "bsr_rbcasecondarycontactid"): Xrm.LookupControl<"contact">;
      get(name: "bsr_recommendedrejectionreason"): Xrm.StringControl;
      get(name: "bsr_registrationcommencementdate"): Xrm.DateControl;
      get(name: "bsr_regulatorydecisionstatus"): Xrm.OptionSetControl<bsr_regulatorydecisionstatus>;
      get(name: "bsr_reviewdecision"): Xrm.StringControl;
      get(name: "bsr_reviewstatus"): Xrm.OptionSetControl<bsr_reviewstatus>;
      get(name: "bsr_secondarycontactposition"): Xrm.StringControl;
      get(name: "bsr_sizoeoforgcode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_bsr_sizoeoforgcode>;
      get(name: "bsr_tellusaboutanyotherrelevantbusinesseswhich"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_typeofbusiness"): Xrm.StringControl;
      get(name: "goveukpayments"): Xrm.SubGridControl<"bsr_payment">;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_statuscode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_statuscode>;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "BIClassInfoTab"): Xrm.PageTab<Tabs.BIClassInfoTab>;
      get(name: "EmploymentDetails"): Xrm.PageTab<Tabs.EmploymentDetails>;
      get(name: "Memberships"): Xrm.PageTab<Tabs.Memberships>;
      get(name: "competency"): Xrm.PageTab<Tabs.competency>;
      get(name: "rbcainfo"): Xrm.PageTab<Tabs.rbcainfo>;
      get(name: "tab_3"): Xrm.PageTab<Tabs.tab_3>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "bsr_applicantid"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "bsr_assessmentcertnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_assessmentdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_assessmentorganisationid"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "bsr_assessmentstatus"): Xrm.OptionSetAttribute<bsr_assessmentstatus>;
    getAttribute(attributeName: "bsr_buildingproappid"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_buildingprofessiontypecode"): Xrm.OptionSetAttribute<bsr_buildingprofessiontypecode>;
    getAttribute(attributeName: "bsr_cicairregnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_countofrbis"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_countpreregrbis"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_decisioncondition"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_decisiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_decisionreason"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_declarationdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_escalationstatus"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_hasindependentassessment"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_holdreviewdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_isantimoneylaundering"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isbusinessservicesoffered"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isbusregisteredasapprovedins"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_iscomplaints"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isconfirmationofcurrentownersdirectors"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isconflictofinterest"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_iscontractormanagement"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isdataprotection"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isenforcementorprosecution"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isequalitydivertyinclusion"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isformalorgstructure"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_ishascriminalconvictions"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_ishealthsafetywellbeing"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isinternalaudit"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isongoinghighriskbuildingprojects"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isoperatingproceduresprovided"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isrbisnamesprovided"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isrecommendedforrejection"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isrecruitmentandstaffdev"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isrelevantchangessincereg"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_issendregulatorydecisionemail"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isstaffconduct"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_issubjecttoinvestigations"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isunregrbisnamesprovided"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_iswhistleblowing"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_onholdreason"): Xrm.LookupAttribute<"bsr_onholdreason">;
    getAttribute(attributeName: "bsr_primarycontactposition"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_prioritisationcode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_bsr_prioritisationcode>;
    getAttribute(attributeName: "bsr_rbcaaccountid"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "bsr_rbcadeclaration"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_rbcadeclarationfirstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_rbcadeclarationlastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_rbcadeclarationpositioninbusiness"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_rbcaprimarycontactid"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_rbcasecondarycontactid"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_recommendedrejectionreason"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_registrationcommencementdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_regulatorydecisionstatus"): Xrm.OptionSetAttribute<bsr_regulatorydecisionstatus>;
    getAttribute(attributeName: "bsr_reviewdecision"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_reviewstatus"): Xrm.OptionSetAttribute<bsr_reviewstatus>;
    getAttribute(attributeName: "bsr_secondarycontactposition"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_sizoeoforgcode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_bsr_sizoeoforgcode>;
    getAttribute(attributeName: "bsr_tellusaboutanyotherrelevantbusinesseswhich"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_typeofbusiness"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statuscode"): Xrm.OptionSetAttribute<bsr_buildingprofessionapplication_statuscode>;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "BIIndependentAssessments"): Xrm.SubGridControl<"bsr_biindependentassessment">;
    getControl(controlName: "BIRegistrationActivities"): Xrm.SubGridControl<"bsr_biregactivity">;
    getControl(controlName: "BIRegistrationClass"): Xrm.SubGridControl<"bsr_biregclass">;
    getControl(controlName: "BIRegistrationCountries"): Xrm.SubGridControl<"bsr_biregcountry">;
    getControl(controlName: "EmploymentDetails"): Xrm.SubGridControl<"bsr_biemploymentdetail">;
    getControl(controlName: "ProfessionalMemberships"): Xrm.SubGridControl<"bsr_biprofessionalmembership">;
    getControl(controlName: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_registrationregion">;
    getControl(controlName: "bsr_applicantid"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "bsr_assessmentcertnumber"): Xrm.StringControl;
    getControl(controlName: "bsr_assessmentdate"): Xrm.DateControl;
    getControl(controlName: "bsr_assessmentorganisationid"): Xrm.LookupControl<"account">;
    getControl(controlName: "bsr_assessmentstatus"): Xrm.OptionSetControl<bsr_assessmentstatus>;
    getControl(controlName: "bsr_buildingproappid"): Xrm.StringControl;
    getControl(controlName: "bsr_buildingprofessiontypecode"): Xrm.OptionSetControl<bsr_buildingprofessiontypecode>;
    getControl(controlName: "bsr_cicairregnumber"): Xrm.StringControl;
    getControl(controlName: "bsr_countofrbis"): Xrm.StringControl;
    getControl(controlName: "bsr_countpreregrbis"): Xrm.StringControl;
    getControl(controlName: "bsr_decisioncondition"): Xrm.StringControl;
    getControl(controlName: "bsr_decisiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_decisionreason"): Xrm.StringControl;
    getControl(controlName: "bsr_declarationdate"): Xrm.DateControl;
    getControl(controlName: "bsr_escalationstatus"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_hasindependentassessment"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_holdreviewdate"): Xrm.DateControl;
    getControl(controlName: "bsr_isantimoneylaundering"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isbusinessservicesoffered"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isbusregisteredasapprovedins"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_iscomplaints"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isconfirmationofcurrentownersdirectors"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isconflictofinterest"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_iscontractormanagement"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isdataprotection"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isenforcementorprosecution"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isequalitydivertyinclusion"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isformalorgstructure"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_ishascriminalconvictions"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_ishealthsafetywellbeing"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isinternalaudit"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isongoinghighriskbuildingprojects"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isoperatingproceduresprovided"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isrbisnamesprovided"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isrecommendedforrejection"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isrecruitmentandstaffdev"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isrelevantchangessincereg"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_issendregulatorydecisionemail"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isstaffconduct"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_issubjecttoinvestigations"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isunregrbisnamesprovided"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_iswhistleblowing"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_name"): Xrm.StringControl;
    getControl(controlName: "bsr_onholdreason"): Xrm.LookupControl<"bsr_onholdreason">;
    getControl(controlName: "bsr_primarycontactposition"): Xrm.StringControl;
    getControl(controlName: "bsr_prioritisationcode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_bsr_prioritisationcode>;
    getControl(controlName: "bsr_rbcaaccountid"): Xrm.LookupControl<"account">;
    getControl(controlName: "bsr_rbcadeclaration"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_rbcadeclarationfirstname"): Xrm.StringControl;
    getControl(controlName: "bsr_rbcadeclarationlastname"): Xrm.StringControl;
    getControl(controlName: "bsr_rbcadeclarationpositioninbusiness"): Xrm.StringControl;
    getControl(controlName: "bsr_rbcaprimarycontactid"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_rbcasecondarycontactid"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_recommendedrejectionreason"): Xrm.StringControl;
    getControl(controlName: "bsr_registrationcommencementdate"): Xrm.DateControl;
    getControl(controlName: "bsr_regulatorydecisionstatus"): Xrm.OptionSetControl<bsr_regulatorydecisionstatus>;
    getControl(controlName: "bsr_reviewdecision"): Xrm.StringControl;
    getControl(controlName: "bsr_reviewstatus"): Xrm.OptionSetControl<bsr_reviewstatus>;
    getControl(controlName: "bsr_secondarycontactposition"): Xrm.StringControl;
    getControl(controlName: "bsr_sizoeoforgcode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_bsr_sizoeoforgcode>;
    getControl(controlName: "bsr_tellusaboutanyotherrelevantbusinesseswhich"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_typeofbusiness"): Xrm.StringControl;
    getControl(controlName: "goveukpayments"): Xrm.SubGridControl<"bsr_payment">;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_statuscode"): Xrm.OptionSetControl<bsr_buildingprofessionapplication_statuscode>;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
