<?xml version="1.0" ?><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="text" indent="no"/><xsl:template match="/data"><![CDATA[<div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">Dear <span style="background-color:white"><span style="color:black">[applicant]</span></span></span></span></span></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif"><span style="background-color:white"><span style="color:black">We have received the structure and fire safety information for </span></span></span></span></span><span lang="EN-GB" style="font-size:12.0pt"><span style="line-height:115%"><span style="font-family:&quot;Arial&quot;,sans-serif">%buildingName%</span></span></span><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif"><span style="background-color:white"><span style="color:black">&nbsp;as part of application [application reference].</span></span></span></span></span></div>
<div>&nbsp;</div>
<div><span lang="EN-GB" style="font-size:12.0pt"><span style="background-color:white"><span style="line-height:115%"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:black">You can </span></span></span></span></span><span class="MsoHyperlink" style="color:#0563c1"><u style="text-decoration:underline"><span lang="EN-GB" style="font-size:12.0pt"><span style="line-height:115%"><span style="font-family:&quot;Arial&quot;,sans-serif">get a copy of the information you submitted</span></span></span></u></span><span lang="EN-GB" style="font-size:12.0pt"><span style="background-color:white"><span style="line-height:115%"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:black">. </span></span></span></span></span></div>
<div>&nbsp;</div>
<div><strong><span style="font-size:16pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">What happens next</span></span></span></strong></div>
<div>&nbsp;</div>
<div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">We’ll look at the information you have given and compare it to information we already hold.</span></span></span><br>&nbsp;</div>
<div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">We may also contact you if we need further information.</span></span></span><br>&nbsp;</div>
<div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">From the Health and Safety Executive<br>as the Building Safety Regulator</span></span></span><br>&nbsp;</div>
<div><div align="center" style="margin-bottom:16px; text-align:center"><hr align="center" size="2" width="100%"></div><span style="font-size:12pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif">Do not reply to this email. It’s an automatic message from an unmonitored account.</span></span></span><br>&nbsp;</div>]]></xsl:template></xsl:stylesheet>