interface bsr_buildingcontrollifecycle_Base extends WebEntity {
  bsr_agreedextensionperiod?: number | null;
  bsr_allbuildinspectionscomplete?: bsr_allbuildinspectionscomplete | null;
  bsr_allrequirementsassessed?: bsr_allrequirementsassessed | null;
  bsr_allrequirementssubmitted?: bsr_allrequirementssubmitted | null;
  bsr_appassesscomplete?: bsr_appassesscomplete | null;
  bsr_appassessdatecomplete?: Date | null;
  bsr_approvaldecisiondate?: Date | null;
  bsr_approvaldecisionissueddate?: Date | null;
  bsr_approvaldocument?: string | null;
  bsr_approvalemail?: string | null;
  bsr_approvalrequirementsdecisiondate?: Date | null;
  bsr_approvalrequirementsdecisionissueddate?: Date | null;
  bsr_approvalrequirementsdocument?: string | null;
  bsr_approvalrequirementsemail?: string | null;
  bsr_approvalrequirementsinformation?: string | null;
  bsr_assessmentofrequirements?: boolean | null;
  bsr_assessmentofrequirementsoutcome?: bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome | null;
  bsr_assessrecordsdatefinalised?: Date | null;
  bsr_assesssuccesscriteria?: boolean | null;
  bsr_bcaaapproval?: boolean | null;
  bsr_bcaaapprovalrequirements?: boolean | null;
  bsr_bcaarejection?: boolean | null;
  bsr_bclreference?: string | null;
  bsr_bsr_fireereceipt?: bsr_receiptofconsultation | null;
  bsr_bsr_seweragereceipt?: bsr_receiptofconsultation | null;
  bsr_buildenddate?: Date | null;
  bsr_buildingcontrollifecycleid?: string | null;
  bsr_buildingcontrollifecyclestatus?: bsr_buildingcontrollifecyclestatus | null;
  bsr_buildingname?: string | null;
  bsr_buildinspectionscompletedate?: Date | null;
  bsr_ccfirereceipt?: bsr_ccfirereceiptchoice | null;
  bsr_ccseweragereceipt?: bsr_ccfirereceiptchoice | null;
  bsr_changecontrol?: boolean | null;
  bsr_dutyholderagreement?: boolean | null;
  bsr_dutyholderagreementemail?: string | null;
  bsr_finaliseassessrecords?: bsr_finaliseassessrecords | null;
  bsr_fireconsultationurl?: string | null;
  bsr_fireconsulteereceiveddate?: Date | null;
  bsr_fireconsulteerequestdate?: Date | null;
  bsr_fireconsulteetimer?: Date | null;
  bsr_fireextensionagreed?: boolean | null;
  bsr_fireextensionagreement?: string | null;
  bsr_fireextensionrequest?: string | null;
  bsr_fireextensionrequired?: boolean | null;
  bsr_firerequestemailurl?: string | null;
  bsr_isbuildcomplete?: bsr_isbuildcomplete | null;
  bsr_lifecyclecancellationreason?: bsr_lifecyclecancellationreason | null;
  bsr_lifecyclecompletionreason?: bsr_lifecyclecompletionreason | null;
  bsr_lifecyclephase?: bsr_lifecyclephase | null;
  bsr_mandatorytimelinefailuredate?: Date | null;
  bsr_name?: string | null;
  bsr_numberofrequirements?: number | null;
  bsr_outcomedecisionissueddate?: Date | null;
  bsr_outcomedocument?: string | null;
  bsr_outcomeemail?: string | null;
  bsr_outcomeinformation?: string | null;
  bsr_outstandingissueschecked?: bsr_outstandingissueschecked | null;
  bsr_outstandingissuesdatecompleted?: Date | null;
  bsr_reasonrequired?: string | null;
  bsr_receiptoffireforcompletion?: bsr_buildingcontrollifecycle_bsr_receiptoffireforcompletion | null;
  bsr_receiptofsewerageforcompletion?: bsr_buildingcontrollifecycle_bsr_receiptofsewerageforcompletion | null;
  bsr_receiveddate?: Date | null;
  bsr_regtaskscheduledatecreated?: Date | null;
  bsr_regulatorytaskschedulecreated?: bsr_regulatorytaskschedulecreated | null;
  bsr_rejectiondecisiondate?: Date | null;
  bsr_rejectiondecisionissueddate?: Date | null;
  bsr_rejectiondocument?: string | null;
  bsr_rejectionemail?: string | null;
  bsr_rejectionreasons?: string | null;
  bsr_requirementrequest?: string | null;
  bsr_requirementsubmissiondate?: Date | null;
  bsr_sewerageconsultationreceiveddate?: Date | null;
  bsr_sewerageconsultationrequestdate?: Date | null;
  bsr_sewerageconsultationurl?: string | null;
  bsr_sewerageconsulttimer?: Date | null;
  bsr_sewerageextensionagreed?: boolean | null;
  bsr_sewerageextensionagreement?: string | null;
  bsr_sewerageextensionrequired?: boolean | null;
  bsr_seweragerequestemailurl?: string | null;
  bsr_seweragerxtensionrequest?: string | null;
  bsr_statfireconsultfailuredate?: Date | null;
  bsr_statfireconsultsuccess?: boolean | null;
  bsr_statsewerconsultfailuredate?: Date | null;
  bsr_statsewerconsultsuccess?: boolean | null;
  bsr_timeextensionemail?: string | null;
  bsr_timerequirement?: number | null;
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: bsr_buildingcontrollifecycle_statecode | null;
  statuscode?: bsr_buildingcontrollifecycle_statuscode | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface bsr_buildingcontrollifecycle_Relationships {
  bsr_bsr_buildingcontrollifecycle_bsr_buildingcontrollifecycle_supportingbcl?: bsr_buildingcontrollifecycle_Result[] | null;
  bsr_bsr_buildingcontrollifecycle_bsr_changerequest_buildingcontrollifecycleid?: bsr_changerequest_Result[] | null;
  bsr_buildingdetails_buildingcontrollifecycle?: bsr_buildingdetails_Result[] | null;
}
interface bsr_buildingcontrollifecycle extends bsr_buildingcontrollifecycle_Base, bsr_buildingcontrollifecycle_Relationships {
  bsr_bcaaapplication_bind$bsr_buildingcontrolapplications?: string | null;
  bsr_bclrcaseofficer_bind$systemusers?: string | null;
  bsr_buildingdetails_bind$bsr_buildingdetailses?: string | null;
  bsr_completioncertappid_bind$bsr_buildingcontrolapplications?: string | null;
  bsr_fireconsultee_bind$contacts?: string | null;
  bsr_reglead_bind$systemusers?: string | null;
  bsr_sewerageundertaker_bind$contacts?: string | null;
  bsr_supportingbcl_bind$bsr_buildingcontrollifecycles?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
}
interface bsr_buildingcontrollifecycle_Create extends bsr_buildingcontrollifecycle {
}
interface bsr_buildingcontrollifecycle_Update extends bsr_buildingcontrollifecycle {
}
interface bsr_buildingcontrollifecycle_Select {
  bsr_agreedextensionperiod: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_agreedextensionperiod: number | null }, {  }>;
  bsr_allbuildinspectionscomplete: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_allbuildinspectionscomplete: bsr_allbuildinspectionscomplete | null }, { bsr_allbuildinspectionscomplete_formatted?: string }>;
  bsr_allrequirementsassessed: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_allrequirementsassessed: bsr_allrequirementsassessed | null }, { bsr_allrequirementsassessed_formatted?: string }>;
  bsr_allrequirementssubmitted: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_allrequirementssubmitted: bsr_allrequirementssubmitted | null }, { bsr_allrequirementssubmitted_formatted?: string }>;
  bsr_appassesscomplete: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_appassesscomplete: bsr_appassesscomplete | null }, { bsr_appassesscomplete_formatted?: string }>;
  bsr_appassessdatecomplete: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_appassessdatecomplete: Date | null }, { bsr_appassessdatecomplete_formatted?: string }>;
  bsr_approvaldecisiondate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvaldecisiondate: Date | null }, { bsr_approvaldecisiondate_formatted?: string }>;
  bsr_approvaldecisionissueddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvaldecisionissueddate: Date | null }, { bsr_approvaldecisionissueddate_formatted?: string }>;
  bsr_approvaldocument: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvaldocument: string | null }, {  }>;
  bsr_approvalemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalemail: string | null }, {  }>;
  bsr_approvalrequirementsdecisiondate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalrequirementsdecisiondate: Date | null }, { bsr_approvalrequirementsdecisiondate_formatted?: string }>;
  bsr_approvalrequirementsdecisionissueddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalrequirementsdecisionissueddate: Date | null }, { bsr_approvalrequirementsdecisionissueddate_formatted?: string }>;
  bsr_approvalrequirementsdocument: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalrequirementsdocument: string | null }, {  }>;
  bsr_approvalrequirementsemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalrequirementsemail: string | null }, {  }>;
  bsr_approvalrequirementsinformation: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_approvalrequirementsinformation: string | null }, {  }>;
  bsr_assessmentofrequirements: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_assessmentofrequirements: boolean | null }, {  }>;
  bsr_assessmentofrequirementsoutcome: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_assessmentofrequirementsoutcome: bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome | null }, { bsr_assessmentofrequirementsoutcome_formatted?: string }>;
  bsr_assessrecordsdatefinalised: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_assessrecordsdatefinalised: Date | null }, { bsr_assessrecordsdatefinalised_formatted?: string }>;
  bsr_assesssuccesscriteria: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_assesssuccesscriteria: boolean | null }, {  }>;
  bsr_bcaaapplication_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bcaaapplication_guid: string | null }, { bsr_bcaaapplication_formatted?: string }>;
  bsr_bcaaapproval: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bcaaapproval: boolean | null }, {  }>;
  bsr_bcaaapprovalrequirements: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bcaaapprovalrequirements: boolean | null }, {  }>;
  bsr_bcaarejection: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bcaarejection: boolean | null }, {  }>;
  bsr_bclrcaseofficer_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bclrcaseofficer_guid: string | null }, { bsr_bclrcaseofficer_formatted?: string }>;
  bsr_bclreference: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bclreference: string | null }, {  }>;
  bsr_bsr_fireereceipt: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bsr_fireereceipt: bsr_receiptofconsultation | null }, { bsr_bsr_fireereceipt_formatted?: string }>;
  bsr_bsr_seweragereceipt: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_bsr_seweragereceipt: bsr_receiptofconsultation | null }, { bsr_bsr_seweragereceipt_formatted?: string }>;
  bsr_buildenddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildenddate: Date | null }, { bsr_buildenddate_formatted?: string }>;
  bsr_buildingcontrollifecycleid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildingcontrollifecycleid: string | null }, {  }>;
  bsr_buildingcontrollifecyclestatus: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildingcontrollifecyclestatus: bsr_buildingcontrollifecyclestatus | null }, { bsr_buildingcontrollifecyclestatus_formatted?: string }>;
  bsr_buildingdetails_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildingdetails_guid: string | null }, { bsr_buildingdetails_formatted?: string }>;
  bsr_buildingname: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildingname: string | null }, {  }>;
  bsr_buildinspectionscompletedate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_buildinspectionscompletedate: Date | null }, { bsr_buildinspectionscompletedate_formatted?: string }>;
  bsr_ccfirereceipt: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_ccfirereceipt: bsr_ccfirereceiptchoice | null }, { bsr_ccfirereceipt_formatted?: string }>;
  bsr_ccseweragereceipt: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_ccseweragereceipt: bsr_ccfirereceiptchoice | null }, { bsr_ccseweragereceipt_formatted?: string }>;
  bsr_changecontrol: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_changecontrol: boolean | null }, {  }>;
  bsr_completioncertappid_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_completioncertappid_guid: string | null }, { bsr_completioncertappid_formatted?: string }>;
  bsr_dutyholderagreement: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_dutyholderagreement: boolean | null }, {  }>;
  bsr_dutyholderagreementemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_dutyholderagreementemail: string | null }, {  }>;
  bsr_finaliseassessrecords: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_finaliseassessrecords: bsr_finaliseassessrecords | null }, { bsr_finaliseassessrecords_formatted?: string }>;
  bsr_fireconsultationurl: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireconsultationurl: string | null }, {  }>;
  bsr_fireconsultee_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireconsultee_guid: string | null }, { bsr_fireconsultee_formatted?: string }>;
  bsr_fireconsulteereceiveddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireconsulteereceiveddate: Date | null }, { bsr_fireconsulteereceiveddate_formatted?: string }>;
  bsr_fireconsulteerequestdate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireconsulteerequestdate: Date | null }, { bsr_fireconsulteerequestdate_formatted?: string }>;
  bsr_fireconsulteetimer: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireconsulteetimer: Date | null }, { bsr_fireconsulteetimer_formatted?: string }>;
  bsr_fireextensionagreed: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireextensionagreed: boolean | null }, {  }>;
  bsr_fireextensionagreement: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireextensionagreement: string | null }, {  }>;
  bsr_fireextensionrequest: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireextensionrequest: string | null }, {  }>;
  bsr_fireextensionrequired: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_fireextensionrequired: boolean | null }, {  }>;
  bsr_firerequestemailurl: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_firerequestemailurl: string | null }, {  }>;
  bsr_isbuildcomplete: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_isbuildcomplete: bsr_isbuildcomplete | null }, { bsr_isbuildcomplete_formatted?: string }>;
  bsr_lifecyclecancellationreason: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_lifecyclecancellationreason: bsr_lifecyclecancellationreason | null }, { bsr_lifecyclecancellationreason_formatted?: string }>;
  bsr_lifecyclecompletionreason: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_lifecyclecompletionreason: bsr_lifecyclecompletionreason | null }, { bsr_lifecyclecompletionreason_formatted?: string }>;
  bsr_lifecyclephase: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_lifecyclephase: bsr_lifecyclephase | null }, { bsr_lifecyclephase_formatted?: string }>;
  bsr_mandatorytimelinefailuredate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_mandatorytimelinefailuredate: Date | null }, { bsr_mandatorytimelinefailuredate_formatted?: string }>;
  bsr_name: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_name: string | null }, {  }>;
  bsr_numberofrequirements: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_numberofrequirements: number | null }, {  }>;
  bsr_outcomedecisionissueddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outcomedecisionissueddate: Date | null }, { bsr_outcomedecisionissueddate_formatted?: string }>;
  bsr_outcomedocument: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outcomedocument: string | null }, {  }>;
  bsr_outcomeemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outcomeemail: string | null }, {  }>;
  bsr_outcomeinformation: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outcomeinformation: string | null }, {  }>;
  bsr_outstandingissueschecked: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outstandingissueschecked: bsr_outstandingissueschecked | null }, { bsr_outstandingissueschecked_formatted?: string }>;
  bsr_outstandingissuesdatecompleted: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_outstandingissuesdatecompleted: Date | null }, { bsr_outstandingissuesdatecompleted_formatted?: string }>;
  bsr_reasonrequired: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_reasonrequired: string | null }, {  }>;
  bsr_receiptoffireforcompletion: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_receiptoffireforcompletion: bsr_buildingcontrollifecycle_bsr_receiptoffireforcompletion | null }, { bsr_receiptoffireforcompletion_formatted?: string }>;
  bsr_receiptofsewerageforcompletion: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_receiptofsewerageforcompletion: bsr_buildingcontrollifecycle_bsr_receiptofsewerageforcompletion | null }, { bsr_receiptofsewerageforcompletion_formatted?: string }>;
  bsr_receiveddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_receiveddate: Date | null }, { bsr_receiveddate_formatted?: string }>;
  bsr_reglead_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_reglead_guid: string | null }, { bsr_reglead_formatted?: string }>;
  bsr_regtaskscheduledatecreated: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_regtaskscheduledatecreated: Date | null }, { bsr_regtaskscheduledatecreated_formatted?: string }>;
  bsr_regulatorytaskschedulecreated: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_regulatorytaskschedulecreated: bsr_regulatorytaskschedulecreated | null }, { bsr_regulatorytaskschedulecreated_formatted?: string }>;
  bsr_rejectiondecisiondate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_rejectiondecisiondate: Date | null }, { bsr_rejectiondecisiondate_formatted?: string }>;
  bsr_rejectiondecisionissueddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_rejectiondecisionissueddate: Date | null }, { bsr_rejectiondecisionissueddate_formatted?: string }>;
  bsr_rejectiondocument: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_rejectiondocument: string | null }, {  }>;
  bsr_rejectionemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_rejectionemail: string | null }, {  }>;
  bsr_rejectionreasons: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_rejectionreasons: string | null }, {  }>;
  bsr_requirementrequest: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_requirementrequest: string | null }, {  }>;
  bsr_requirementsubmissiondate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_requirementsubmissiondate: Date | null }, { bsr_requirementsubmissiondate_formatted?: string }>;
  bsr_sewerageconsultationreceiveddate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageconsultationreceiveddate: Date | null }, { bsr_sewerageconsultationreceiveddate_formatted?: string }>;
  bsr_sewerageconsultationrequestdate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageconsultationrequestdate: Date | null }, { bsr_sewerageconsultationrequestdate_formatted?: string }>;
  bsr_sewerageconsultationurl: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageconsultationurl: string | null }, {  }>;
  bsr_sewerageconsulttimer: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageconsulttimer: Date | null }, { bsr_sewerageconsulttimer_formatted?: string }>;
  bsr_sewerageextensionagreed: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageextensionagreed: boolean | null }, {  }>;
  bsr_sewerageextensionagreement: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageextensionagreement: string | null }, {  }>;
  bsr_sewerageextensionrequired: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageextensionrequired: boolean | null }, {  }>;
  bsr_seweragerequestemailurl: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_seweragerequestemailurl: string | null }, {  }>;
  bsr_seweragerxtensionrequest: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_seweragerxtensionrequest: string | null }, {  }>;
  bsr_sewerageundertaker_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_sewerageundertaker_guid: string | null }, { bsr_sewerageundertaker_formatted?: string }>;
  bsr_statfireconsultfailuredate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_statfireconsultfailuredate: Date | null }, { bsr_statfireconsultfailuredate_formatted?: string }>;
  bsr_statfireconsultsuccess: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_statfireconsultsuccess: boolean | null }, {  }>;
  bsr_statsewerconsultfailuredate: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_statsewerconsultfailuredate: Date | null }, { bsr_statsewerconsultfailuredate_formatted?: string }>;
  bsr_statsewerconsultsuccess: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_statsewerconsultsuccess: boolean | null }, {  }>;
  bsr_supportingbcl_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_supportingbcl_guid: string | null }, { bsr_supportingbcl_formatted?: string }>;
  bsr_timeextensionemail: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_timeextensionemail: string | null }, {  }>;
  bsr_timerequirement: WebAttribute<bsr_buildingcontrollifecycle_Select, { bsr_timerequirement: number | null }, {  }>;
  createdby_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<bsr_buildingcontrollifecycle_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<bsr_buildingcontrollifecycle_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<bsr_buildingcontrollifecycle_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  overriddencreatedon: WebAttribute<bsr_buildingcontrollifecycle_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<bsr_buildingcontrollifecycle_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<bsr_buildingcontrollifecycle_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<bsr_buildingcontrollifecycle_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<bsr_buildingcontrollifecycle_Select, { statecode: bsr_buildingcontrollifecycle_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<bsr_buildingcontrollifecycle_Select, { statuscode: bsr_buildingcontrollifecycle_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<bsr_buildingcontrollifecycle_Select, { timezoneruleversionnumber: number | null }, {  }>;
  traversedpath: WebAttribute<bsr_buildingcontrollifecycle_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<bsr_buildingcontrollifecycle_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<bsr_buildingcontrollifecycle_Select, { versionnumber: number | null }, {  }>;
}
interface bsr_buildingcontrollifecycle_Filter {
  bsr_agreedextensionperiod: number;
  bsr_allbuildinspectionscomplete: bsr_allbuildinspectionscomplete;
  bsr_allrequirementsassessed: bsr_allrequirementsassessed;
  bsr_allrequirementssubmitted: bsr_allrequirementssubmitted;
  bsr_appassesscomplete: bsr_appassesscomplete;
  bsr_appassessdatecomplete: Date;
  bsr_approvaldecisiondate: Date;
  bsr_approvaldecisionissueddate: Date;
  bsr_approvaldocument: string;
  bsr_approvalemail: string;
  bsr_approvalrequirementsdecisiondate: Date;
  bsr_approvalrequirementsdecisionissueddate: Date;
  bsr_approvalrequirementsdocument: string;
  bsr_approvalrequirementsemail: string;
  bsr_approvalrequirementsinformation: string;
  bsr_assessmentofrequirements: boolean;
  bsr_assessmentofrequirementsoutcome: bsr_buildingcontrollifecycle_bsr_assessmentofrequirementsoutcome;
  bsr_assessrecordsdatefinalised: Date;
  bsr_assesssuccesscriteria: boolean;
  bsr_bcaaapplication_guid: XQW.Guid;
  bsr_bcaaapproval: boolean;
  bsr_bcaaapprovalrequirements: boolean;
  bsr_bcaarejection: boolean;
  bsr_bclrcaseofficer_guid: XQW.Guid;
  bsr_bclreference: string;
  bsr_bsr_fireereceipt: bsr_receiptofconsultation;
  bsr_bsr_seweragereceipt: bsr_receiptofconsultation;
  bsr_buildenddate: Date;
  bsr_buildingcontrollifecycleid: XQW.Guid;
  bsr_buildingcontrollifecyclestatus: bsr_buildingcontrollifecyclestatus;
  bsr_buildingdetails_guid: XQW.Guid;
  bsr_buildingname: string;
  bsr_buildinspectionscompletedate: Date;
  bsr_ccfirereceipt: bsr_ccfirereceiptchoice;
  bsr_ccseweragereceipt: bsr_ccfirereceiptchoice;
  bsr_changecontrol: boolean;
  bsr_completioncertappid_guid: XQW.Guid;
  bsr_dutyholderagreement: boolean;
  bsr_dutyholderagreementemail: string;
  bsr_finaliseassessrecords: bsr_finaliseassessrecords;
  bsr_fireconsultationurl: string;
  bsr_fireconsultee_guid: XQW.Guid;
  bsr_fireconsulteereceiveddate: Date;
  bsr_fireconsulteerequestdate: Date;
  bsr_fireconsulteetimer: Date;
  bsr_fireextensionagreed: boolean;
  bsr_fireextensionagreement: string;
  bsr_fireextensionrequest: string;
  bsr_fireextensionrequired: boolean;
  bsr_firerequestemailurl: string;
  bsr_isbuildcomplete: bsr_isbuildcomplete;
  bsr_lifecyclecancellationreason: bsr_lifecyclecancellationreason;
  bsr_lifecyclecompletionreason: bsr_lifecyclecompletionreason;
  bsr_lifecyclephase: bsr_lifecyclephase;
  bsr_mandatorytimelinefailuredate: Date;
  bsr_name: string;
  bsr_numberofrequirements: number;
  bsr_outcomedecisionissueddate: Date;
  bsr_outcomedocument: string;
  bsr_outcomeemail: string;
  bsr_outcomeinformation: string;
  bsr_outstandingissueschecked: bsr_outstandingissueschecked;
  bsr_outstandingissuesdatecompleted: Date;
  bsr_reasonrequired: string;
  bsr_receiptoffireforcompletion: bsr_buildingcontrollifecycle_bsr_receiptoffireforcompletion;
  bsr_receiptofsewerageforcompletion: bsr_buildingcontrollifecycle_bsr_receiptofsewerageforcompletion;
  bsr_receiveddate: Date;
  bsr_reglead_guid: XQW.Guid;
  bsr_regtaskscheduledatecreated: Date;
  bsr_regulatorytaskschedulecreated: bsr_regulatorytaskschedulecreated;
  bsr_rejectiondecisiondate: Date;
  bsr_rejectiondecisionissueddate: Date;
  bsr_rejectiondocument: string;
  bsr_rejectionemail: string;
  bsr_rejectionreasons: string;
  bsr_requirementrequest: string;
  bsr_requirementsubmissiondate: Date;
  bsr_sewerageconsultationreceiveddate: Date;
  bsr_sewerageconsultationrequestdate: Date;
  bsr_sewerageconsultationurl: string;
  bsr_sewerageconsulttimer: Date;
  bsr_sewerageextensionagreed: boolean;
  bsr_sewerageextensionagreement: string;
  bsr_sewerageextensionrequired: boolean;
  bsr_seweragerequestemailurl: string;
  bsr_seweragerxtensionrequest: string;
  bsr_sewerageundertaker_guid: XQW.Guid;
  bsr_statfireconsultfailuredate: Date;
  bsr_statfireconsultsuccess: boolean;
  bsr_statsewerconsultfailuredate: Date;
  bsr_statsewerconsultsuccess: boolean;
  bsr_supportingbcl_guid: XQW.Guid;
  bsr_timeextensionemail: string;
  bsr_timerequirement: number;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: bsr_buildingcontrollifecycle_statecode;
  statuscode: bsr_buildingcontrollifecycle_statuscode;
  timezoneruleversionnumber: number;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface bsr_buildingcontrollifecycle_Expand {
  bsr_bcaaapplication: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingcontrolapplication_Select, bsr_buildingcontrolapplication_Filter, { bsr_bcaaapplication: bsr_buildingcontrolapplication_Result }>;
  bsr_bsr_buildingcontrollifecycle_bsr_buildingcontrollifecycle_supportingbcl: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingcontrollifecycle_Select, bsr_buildingcontrollifecycle_Filter, { bsr_bsr_buildingcontrollifecycle_bsr_buildingcontrollifecycle_supportingbcl: bsr_buildingcontrollifecycle_Result[] }>;
  bsr_bsr_buildingcontrollifecycle_bsr_changerequest_buildingcontrollifecycleid: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_changerequest_Select, bsr_changerequest_Filter, { bsr_bsr_buildingcontrollifecycle_bsr_changerequest_buildingcontrollifecycleid: bsr_changerequest_Result[] }>;
  bsr_buildingdetails: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingdetails_Select, bsr_buildingdetails_Filter, { bsr_buildingdetails: bsr_buildingdetails_Result }>;
  bsr_buildingdetails_buildingcontrollifecycle: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingdetails_Select, bsr_buildingdetails_Filter, { bsr_buildingdetails_buildingcontrollifecycle: bsr_buildingdetails_Result[] }>;
  bsr_completioncertappid: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingcontrolapplication_Select, bsr_buildingcontrolapplication_Filter, { bsr_completioncertappid: bsr_buildingcontrolapplication_Result }>;
  bsr_supportingbcl: WebExpand<bsr_buildingcontrollifecycle_Expand, bsr_buildingcontrollifecycle_Select, bsr_buildingcontrollifecycle_Filter, { bsr_supportingbcl: bsr_buildingcontrollifecycle_Result }>;
}
interface bsr_buildingcontrollifecycle_FormattedResult {
  bsr_allbuildinspectionscomplete_formatted?: string;
  bsr_allrequirementsassessed_formatted?: string;
  bsr_allrequirementssubmitted_formatted?: string;
  bsr_appassesscomplete_formatted?: string;
  bsr_appassessdatecomplete_formatted?: string;
  bsr_approvaldecisiondate_formatted?: string;
  bsr_approvaldecisionissueddate_formatted?: string;
  bsr_approvalrequirementsdecisiondate_formatted?: string;
  bsr_approvalrequirementsdecisionissueddate_formatted?: string;
  bsr_assessmentofrequirementsoutcome_formatted?: string;
  bsr_assessrecordsdatefinalised_formatted?: string;
  bsr_bcaaapplication_formatted?: string;
  bsr_bclrcaseofficer_formatted?: string;
  bsr_bsr_fireereceipt_formatted?: string;
  bsr_bsr_seweragereceipt_formatted?: string;
  bsr_buildenddate_formatted?: string;
  bsr_buildingcontrollifecyclestatus_formatted?: string;
  bsr_buildingdetails_formatted?: string;
  bsr_buildinspectionscompletedate_formatted?: string;
  bsr_ccfirereceipt_formatted?: string;
  bsr_ccseweragereceipt_formatted?: string;
  bsr_completioncertappid_formatted?: string;
  bsr_finaliseassessrecords_formatted?: string;
  bsr_fireconsultee_formatted?: string;
  bsr_fireconsulteereceiveddate_formatted?: string;
  bsr_fireconsulteerequestdate_formatted?: string;
  bsr_fireconsulteetimer_formatted?: string;
  bsr_isbuildcomplete_formatted?: string;
  bsr_lifecyclecancellationreason_formatted?: string;
  bsr_lifecyclecompletionreason_formatted?: string;
  bsr_lifecyclephase_formatted?: string;
  bsr_mandatorytimelinefailuredate_formatted?: string;
  bsr_outcomedecisionissueddate_formatted?: string;
  bsr_outstandingissueschecked_formatted?: string;
  bsr_outstandingissuesdatecompleted_formatted?: string;
  bsr_receiptoffireforcompletion_formatted?: string;
  bsr_receiptofsewerageforcompletion_formatted?: string;
  bsr_receiveddate_formatted?: string;
  bsr_reglead_formatted?: string;
  bsr_regtaskscheduledatecreated_formatted?: string;
  bsr_regulatorytaskschedulecreated_formatted?: string;
  bsr_rejectiondecisiondate_formatted?: string;
  bsr_rejectiondecisionissueddate_formatted?: string;
  bsr_requirementsubmissiondate_formatted?: string;
  bsr_sewerageconsultationreceiveddate_formatted?: string;
  bsr_sewerageconsultationrequestdate_formatted?: string;
  bsr_sewerageconsulttimer_formatted?: string;
  bsr_sewerageundertaker_formatted?: string;
  bsr_statfireconsultfailuredate_formatted?: string;
  bsr_statsewerconsultfailuredate_formatted?: string;
  bsr_supportingbcl_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface bsr_buildingcontrollifecycle_Result extends bsr_buildingcontrollifecycle_Base, bsr_buildingcontrollifecycle_Relationships {
  "@odata.etag": string;
  bsr_bcaaapplication_guid: string | null;
  bsr_bclrcaseofficer_guid: string | null;
  bsr_buildingdetails_guid: string | null;
  bsr_completioncertappid_guid: string | null;
  bsr_fireconsultee_guid: string | null;
  bsr_reglead_guid: string | null;
  bsr_sewerageundertaker_guid: string | null;
  bsr_supportingbcl_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface bsr_buildingcontrollifecycle_RelatedOne {
  bsr_bcaaapplication: WebMappingRetrieve<bsr_buildingcontrolapplication_Select,bsr_buildingcontrolapplication_Expand,bsr_buildingcontrolapplication_Filter,bsr_buildingcontrolapplication_Fixed,bsr_buildingcontrolapplication_Result,bsr_buildingcontrolapplication_FormattedResult>;
  bsr_buildingdetails: WebMappingRetrieve<bsr_buildingdetails_Select,bsr_buildingdetails_Expand,bsr_buildingdetails_Filter,bsr_buildingdetails_Fixed,bsr_buildingdetails_Result,bsr_buildingdetails_FormattedResult>;
  bsr_completioncertappid: WebMappingRetrieve<bsr_buildingcontrolapplication_Select,bsr_buildingcontrolapplication_Expand,bsr_buildingcontrolapplication_Filter,bsr_buildingcontrolapplication_Fixed,bsr_buildingcontrolapplication_Result,bsr_buildingcontrolapplication_FormattedResult>;
  bsr_supportingbcl: WebMappingRetrieve<bsr_buildingcontrollifecycle_Select,bsr_buildingcontrollifecycle_Expand,bsr_buildingcontrollifecycle_Filter,bsr_buildingcontrollifecycle_Fixed,bsr_buildingcontrollifecycle_Result,bsr_buildingcontrollifecycle_FormattedResult>;
}
interface bsr_buildingcontrollifecycle_RelatedMany {
  bsr_bsr_buildingcontrollifecycle_bsr_buildingcontrollifecycle_supportingbcl: WebMappingRetrieve<bsr_buildingcontrollifecycle_Select,bsr_buildingcontrollifecycle_Expand,bsr_buildingcontrollifecycle_Filter,bsr_buildingcontrollifecycle_Fixed,bsr_buildingcontrollifecycle_Result,bsr_buildingcontrollifecycle_FormattedResult>;
  bsr_bsr_buildingcontrollifecycle_bsr_changerequest_buildingcontrollifecycleid: WebMappingRetrieve<bsr_changerequest_Select,bsr_changerequest_Expand,bsr_changerequest_Filter,bsr_changerequest_Fixed,bsr_changerequest_Result,bsr_changerequest_FormattedResult>;
  bsr_buildingdetails_buildingcontrollifecycle: WebMappingRetrieve<bsr_buildingdetails_Select,bsr_buildingdetails_Expand,bsr_buildingdetails_Filter,bsr_buildingdetails_Fixed,bsr_buildingdetails_Result,bsr_buildingdetails_FormattedResult>;
}
interface WebEntitiesRetrieve {
  bsr_buildingcontrollifecycles: WebMappingRetrieve<bsr_buildingcontrollifecycle_Select,bsr_buildingcontrollifecycle_Expand,bsr_buildingcontrollifecycle_Filter,bsr_buildingcontrollifecycle_Fixed,bsr_buildingcontrollifecycle_Result,bsr_buildingcontrollifecycle_FormattedResult>;
}
interface WebEntitiesRelated {
  bsr_buildingcontrollifecycles: WebMappingRelated<bsr_buildingcontrollifecycle_RelatedOne,bsr_buildingcontrollifecycle_RelatedMany>;
}
interface WebEntitiesCUDA {
  bsr_buildingcontrollifecycles: WebMappingCUDA<bsr_buildingcontrollifecycle_Create,bsr_buildingcontrollifecycle_Update,bsr_buildingcontrollifecycle_Select>;
}
