interface bsr_buildingdetails_Base extends WebEntity {
  bsr_address1_city?: string | null;
  bsr_address1_line1?: string | null;
  bsr_address1_line2?: string | null;
  bsr_address1_postalcode?: string | null;
  bsr_buildingaddressmanual?: boolean | null;
  bsr_buildingcategory?: bsr_buildingcategorychoice | null;
  bsr_buildingdetailsid?: string | null;
  bsr_buildingeasting?: number | null;
  bsr_buildinghaveaddress?: boolean | null;
  bsr_buildingnorthing?: number | null;
  bsr_buildingregcompliance?: string | null;
  bsr_buildingregcompliancecata?: string | null;
  bsr_buildingregcompliancecatb?: string | null;
  bsr_buildingregistrationnumber?: string | null;
  bsr_buildoverwithin3mofcentrelineflow?: boolean | null;
  bsr_changebuildingregcompliance?: string | null;
  bsr_changeclientsignedstatement?: string | null;
  bsr_changecompetencedeclaration?: string | null;
  bsr_changeconstructioncontrolplan?: string | null;
  bsr_changecontrolplan?: string | null;
  bsr_changedrawingsandplans?: string | null;
  bsr_changefireemergencyfiles?: string | null;
  bsr_changeheight?: number | null;
  bsr_changemorplan?: string | null;
  bsr_changenonresidentialunits?: number | null;
  bsr_changenumberofresidentialunits?: number | null;
  bsr_changenumberstoreys?: number | null;
  bsr_changeplannedbuildtime?: number | null;
  bsr_changeplanningstatement?: string | null;
  bsr_changeprimaryuse?: bsr_primaryusechoice | null;
  bsr_changeuseofeachstory?: string | null;
  bsr_changeworksdescription?: string | null;
  bsr_clientsignedstatement?: string | null;
  bsr_clientsignedstatementcata?: string | null;
  bsr_clientsignedstatementcatb?: string | null;
  bsr_competencedeclaration?: string | null;
  bsr_competencedeclarationcata?: string | null;
  bsr_competencedeclarationcatb?: string | null;
  bsr_constructioncontrolplan?: string | null;
  bsr_constructioncontrolplancata?: string | null;
  bsr_constructioncontrolplancatb?: string | null;
  bsr_currentheight?: number | null;
  bsr_currentheightproposed?: number | null;
  bsr_currentnonresidentialunits?: number | null;
  bsr_currentnonresidentialunitsproposed?: number | null;
  bsr_currentnumberofresidentialunits?: number | null;
  bsr_currentnumberofresidentialunitsproposed?: number | null;
  bsr_currentnumberstoreys?: number | null;
  bsr_currentnumberstoreysproposed?: number | null;
  bsr_currentplannedbuildtimeproposed?: number | null;
  bsr_currentprimaryuse?: bsr_primaryusechoice | null;
  bsr_currentstoreyuse?: string | null;
  bsr_currentuseofeachstoryproposed?: string | null;
  bsr_currentworksdescriptionproposed?: string | null;
  bsr_drainageprecautions?: boolean | null;
  bsr_drawingsandplans?: string | null;
  bsr_drawingsandplanscata?: string | null;
  bsr_drawingsandplanscatb?: string | null;
  bsr_existingusecategory?: bsr_existingusecategorychoice | null;
  bsr_existtypeworkproposal?: bsr_existingusetypeofproposedworkchoic | null;
  bsr_fireemergencyfiles?: string | null;
  bsr_fireemergencyfilescata?: string | null;
  bsr_fireemergencyfilescatb?: string | null;
  bsr_height?: number | null;
  bsr_localenactment?: string | null;
  bsr_localenactmentcompliance?: string | null;
  bsr_morplan?: string | null;
  bsr_morplancata?: string | null;
  bsr_morplancatb?: string | null;
  bsr_name?: string | null;
  bsr_newdrainorsewer?: boolean | null;
  bsr_nonhrb?: boolean | null;
  bsr_numbernonresidentialunits?: number | null;
  bsr_numberresidentialunits?: number | null;
  bsr_numberstoreys?: number | null;
  bsr_partialcompletion?: bsr_partialcompletionchoice | null;
  bsr_partialcompletionstrategy?: string | null;
  bsr_pgo?: string | null;
  bsr_pgoreferencenumber?: string | null;
  bsr_plannedbuildtime?: number | null;
  bsr_planningreferencenumber?: string | null;
  bsr_planningstatement?: string | null;
  bsr_planningstatementcata?: string | null;
  bsr_planningstatementcatb?: string | null;
  bsr_primaryuse?: bsr_primaryusechoice | null;
  bsr_proposedprimaryuse?: bsr_primaryusechoice | null;
  bsr_sitelocationplan?: string | null;
  bsr_sitesharedservices?: bsr_sitesharedserviceschoice | null;
  bsr_sitesharedservicesdetails?: string | null;
  bsr_sitesharedservicesurl?: string | null;
  bsr_storeyuse?: string | null;
  bsr_tellusaboutyourdrainageprecautions?: string | null;
  bsr_workdescription?: string | null;
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  statecode?: bsr_buildingdetails_statecode | null;
  statuscode?: bsr_buildingdetails_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface bsr_buildingdetails_Relationships {
}
interface bsr_buildingdetails extends bsr_buildingdetails_Base, bsr_buildingdetails_Relationships {
  bsr_bcapplicationid_bind$bsr_buildingcontrolapplications?: string | null;
  bsr_buildingcontrollifecycle_bind$bsr_buildingcontrollifecycles?: string | null;
  bsr_buildingid_bind$bsr_buildings?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface bsr_buildingdetails_Create extends bsr_buildingdetails {
}
interface bsr_buildingdetails_Update extends bsr_buildingdetails {
}
interface bsr_buildingdetails_Select {
  bsr_address1_city: WebAttribute<bsr_buildingdetails_Select, { bsr_address1_city: string | null }, {  }>;
  bsr_address1_line1: WebAttribute<bsr_buildingdetails_Select, { bsr_address1_line1: string | null }, {  }>;
  bsr_address1_line2: WebAttribute<bsr_buildingdetails_Select, { bsr_address1_line2: string | null }, {  }>;
  bsr_address1_postalcode: WebAttribute<bsr_buildingdetails_Select, { bsr_address1_postalcode: string | null }, {  }>;
  bsr_bcapplicationid_guid: WebAttribute<bsr_buildingdetails_Select, { bsr_bcapplicationid_guid: string | null }, { bsr_bcapplicationid_formatted?: string }>;
  bsr_buildingaddressmanual: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingaddressmanual: boolean | null }, {  }>;
  bsr_buildingcategory: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingcategory: bsr_buildingcategorychoice | null }, { bsr_buildingcategory_formatted?: string }>;
  bsr_buildingcontrollifecycle_guid: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingcontrollifecycle_guid: string | null }, { bsr_buildingcontrollifecycle_formatted?: string }>;
  bsr_buildingdetailsid: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingdetailsid: string | null }, {  }>;
  bsr_buildingeasting: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingeasting: number | null }, {  }>;
  bsr_buildinghaveaddress: WebAttribute<bsr_buildingdetails_Select, { bsr_buildinghaveaddress: boolean | null }, {  }>;
  bsr_buildingid_guid: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingid_guid: string | null }, { bsr_buildingid_formatted?: string }>;
  bsr_buildingnorthing: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingnorthing: number | null }, {  }>;
  bsr_buildingregcompliance: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingregcompliance: string | null }, {  }>;
  bsr_buildingregcompliancecata: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingregcompliancecata: string | null }, {  }>;
  bsr_buildingregcompliancecatb: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingregcompliancecatb: string | null }, {  }>;
  bsr_buildingregistrationnumber: WebAttribute<bsr_buildingdetails_Select, { bsr_buildingregistrationnumber: string | null }, {  }>;
  bsr_buildoverwithin3mofcentrelineflow: WebAttribute<bsr_buildingdetails_Select, { bsr_buildoverwithin3mofcentrelineflow: boolean | null }, {  }>;
  bsr_changebuildingregcompliance: WebAttribute<bsr_buildingdetails_Select, { bsr_changebuildingregcompliance: string | null }, {  }>;
  bsr_changeclientsignedstatement: WebAttribute<bsr_buildingdetails_Select, { bsr_changeclientsignedstatement: string | null }, {  }>;
  bsr_changecompetencedeclaration: WebAttribute<bsr_buildingdetails_Select, { bsr_changecompetencedeclaration: string | null }, {  }>;
  bsr_changeconstructioncontrolplan: WebAttribute<bsr_buildingdetails_Select, { bsr_changeconstructioncontrolplan: string | null }, {  }>;
  bsr_changecontrolplan: WebAttribute<bsr_buildingdetails_Select, { bsr_changecontrolplan: string | null }, {  }>;
  bsr_changedrawingsandplans: WebAttribute<bsr_buildingdetails_Select, { bsr_changedrawingsandplans: string | null }, {  }>;
  bsr_changefireemergencyfiles: WebAttribute<bsr_buildingdetails_Select, { bsr_changefireemergencyfiles: string | null }, {  }>;
  bsr_changeheight: WebAttribute<bsr_buildingdetails_Select, { bsr_changeheight: number | null }, {  }>;
  bsr_changemorplan: WebAttribute<bsr_buildingdetails_Select, { bsr_changemorplan: string | null }, {  }>;
  bsr_changenonresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_changenonresidentialunits: number | null }, {  }>;
  bsr_changenumberofresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_changenumberofresidentialunits: number | null }, {  }>;
  bsr_changenumberstoreys: WebAttribute<bsr_buildingdetails_Select, { bsr_changenumberstoreys: number | null }, {  }>;
  bsr_changeplannedbuildtime: WebAttribute<bsr_buildingdetails_Select, { bsr_changeplannedbuildtime: number | null }, {  }>;
  bsr_changeplanningstatement: WebAttribute<bsr_buildingdetails_Select, { bsr_changeplanningstatement: string | null }, {  }>;
  bsr_changeprimaryuse: WebAttribute<bsr_buildingdetails_Select, { bsr_changeprimaryuse: bsr_primaryusechoice | null }, { bsr_changeprimaryuse_formatted?: string }>;
  bsr_changeuseofeachstory: WebAttribute<bsr_buildingdetails_Select, { bsr_changeuseofeachstory: string | null }, {  }>;
  bsr_changeworksdescription: WebAttribute<bsr_buildingdetails_Select, { bsr_changeworksdescription: string | null }, {  }>;
  bsr_clientsignedstatement: WebAttribute<bsr_buildingdetails_Select, { bsr_clientsignedstatement: string | null }, {  }>;
  bsr_clientsignedstatementcata: WebAttribute<bsr_buildingdetails_Select, { bsr_clientsignedstatementcata: string | null }, {  }>;
  bsr_clientsignedstatementcatb: WebAttribute<bsr_buildingdetails_Select, { bsr_clientsignedstatementcatb: string | null }, {  }>;
  bsr_competencedeclaration: WebAttribute<bsr_buildingdetails_Select, { bsr_competencedeclaration: string | null }, {  }>;
  bsr_competencedeclarationcata: WebAttribute<bsr_buildingdetails_Select, { bsr_competencedeclarationcata: string | null }, {  }>;
  bsr_competencedeclarationcatb: WebAttribute<bsr_buildingdetails_Select, { bsr_competencedeclarationcatb: string | null }, {  }>;
  bsr_constructioncontrolplan: WebAttribute<bsr_buildingdetails_Select, { bsr_constructioncontrolplan: string | null }, {  }>;
  bsr_constructioncontrolplancata: WebAttribute<bsr_buildingdetails_Select, { bsr_constructioncontrolplancata: string | null }, {  }>;
  bsr_constructioncontrolplancatb: WebAttribute<bsr_buildingdetails_Select, { bsr_constructioncontrolplancatb: string | null }, {  }>;
  bsr_currentheight: WebAttribute<bsr_buildingdetails_Select, { bsr_currentheight: number | null }, {  }>;
  bsr_currentheightproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentheightproposed: number | null }, {  }>;
  bsr_currentnonresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnonresidentialunits: number | null }, {  }>;
  bsr_currentnonresidentialunitsproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnonresidentialunitsproposed: number | null }, {  }>;
  bsr_currentnumberofresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnumberofresidentialunits: number | null }, {  }>;
  bsr_currentnumberofresidentialunitsproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnumberofresidentialunitsproposed: number | null }, {  }>;
  bsr_currentnumberstoreys: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnumberstoreys: number | null }, {  }>;
  bsr_currentnumberstoreysproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentnumberstoreysproposed: number | null }, {  }>;
  bsr_currentplannedbuildtimeproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentplannedbuildtimeproposed: number | null }, {  }>;
  bsr_currentprimaryuse: WebAttribute<bsr_buildingdetails_Select, { bsr_currentprimaryuse: bsr_primaryusechoice | null }, { bsr_currentprimaryuse_formatted?: string }>;
  bsr_currentstoreyuse: WebAttribute<bsr_buildingdetails_Select, { bsr_currentstoreyuse: string | null }, {  }>;
  bsr_currentuseofeachstoryproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentuseofeachstoryproposed: string | null }, {  }>;
  bsr_currentworksdescriptionproposed: WebAttribute<bsr_buildingdetails_Select, { bsr_currentworksdescriptionproposed: string | null }, {  }>;
  bsr_drainageprecautions: WebAttribute<bsr_buildingdetails_Select, { bsr_drainageprecautions: boolean | null }, {  }>;
  bsr_drawingsandplans: WebAttribute<bsr_buildingdetails_Select, { bsr_drawingsandplans: string | null }, {  }>;
  bsr_drawingsandplanscata: WebAttribute<bsr_buildingdetails_Select, { bsr_drawingsandplanscata: string | null }, {  }>;
  bsr_drawingsandplanscatb: WebAttribute<bsr_buildingdetails_Select, { bsr_drawingsandplanscatb: string | null }, {  }>;
  bsr_existingusecategory: WebAttribute<bsr_buildingdetails_Select, { bsr_existingusecategory: bsr_existingusecategorychoice | null }, { bsr_existingusecategory_formatted?: string }>;
  bsr_existtypeworkproposal: WebAttribute<bsr_buildingdetails_Select, { bsr_existtypeworkproposal: bsr_existingusetypeofproposedworkchoic | null }, { bsr_existtypeworkproposal_formatted?: string }>;
  bsr_fireemergencyfiles: WebAttribute<bsr_buildingdetails_Select, { bsr_fireemergencyfiles: string | null }, {  }>;
  bsr_fireemergencyfilescata: WebAttribute<bsr_buildingdetails_Select, { bsr_fireemergencyfilescata: string | null }, {  }>;
  bsr_fireemergencyfilescatb: WebAttribute<bsr_buildingdetails_Select, { bsr_fireemergencyfilescatb: string | null }, {  }>;
  bsr_height: WebAttribute<bsr_buildingdetails_Select, { bsr_height: number | null }, {  }>;
  bsr_localenactment: WebAttribute<bsr_buildingdetails_Select, { bsr_localenactment: string | null }, {  }>;
  bsr_localenactmentcompliance: WebAttribute<bsr_buildingdetails_Select, { bsr_localenactmentcompliance: string | null }, {  }>;
  bsr_morplan: WebAttribute<bsr_buildingdetails_Select, { bsr_morplan: string | null }, {  }>;
  bsr_morplancata: WebAttribute<bsr_buildingdetails_Select, { bsr_morplancata: string | null }, {  }>;
  bsr_morplancatb: WebAttribute<bsr_buildingdetails_Select, { bsr_morplancatb: string | null }, {  }>;
  bsr_name: WebAttribute<bsr_buildingdetails_Select, { bsr_name: string | null }, {  }>;
  bsr_newdrainorsewer: WebAttribute<bsr_buildingdetails_Select, { bsr_newdrainorsewer: boolean | null }, {  }>;
  bsr_nonhrb: WebAttribute<bsr_buildingdetails_Select, { bsr_nonhrb: boolean | null }, {  }>;
  bsr_numbernonresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_numbernonresidentialunits: number | null }, {  }>;
  bsr_numberresidentialunits: WebAttribute<bsr_buildingdetails_Select, { bsr_numberresidentialunits: number | null }, {  }>;
  bsr_numberstoreys: WebAttribute<bsr_buildingdetails_Select, { bsr_numberstoreys: number | null }, {  }>;
  bsr_partialcompletion: WebAttribute<bsr_buildingdetails_Select, { bsr_partialcompletion: bsr_partialcompletionchoice | null }, { bsr_partialcompletion_formatted?: string }>;
  bsr_partialcompletionstrategy: WebAttribute<bsr_buildingdetails_Select, { bsr_partialcompletionstrategy: string | null }, {  }>;
  bsr_pgo: WebAttribute<bsr_buildingdetails_Select, { bsr_pgo: string | null }, {  }>;
  bsr_pgoreferencenumber: WebAttribute<bsr_buildingdetails_Select, { bsr_pgoreferencenumber: string | null }, {  }>;
  bsr_plannedbuildtime: WebAttribute<bsr_buildingdetails_Select, { bsr_plannedbuildtime: number | null }, {  }>;
  bsr_planningreferencenumber: WebAttribute<bsr_buildingdetails_Select, { bsr_planningreferencenumber: string | null }, {  }>;
  bsr_planningstatement: WebAttribute<bsr_buildingdetails_Select, { bsr_planningstatement: string | null }, {  }>;
  bsr_planningstatementcata: WebAttribute<bsr_buildingdetails_Select, { bsr_planningstatementcata: string | null }, {  }>;
  bsr_planningstatementcatb: WebAttribute<bsr_buildingdetails_Select, { bsr_planningstatementcatb: string | null }, {  }>;
  bsr_primaryuse: WebAttribute<bsr_buildingdetails_Select, { bsr_primaryuse: bsr_primaryusechoice | null }, { bsr_primaryuse_formatted?: string }>;
  bsr_proposedprimaryuse: WebAttribute<bsr_buildingdetails_Select, { bsr_proposedprimaryuse: bsr_primaryusechoice | null }, { bsr_proposedprimaryuse_formatted?: string }>;
  bsr_sitelocationplan: WebAttribute<bsr_buildingdetails_Select, { bsr_sitelocationplan: string | null }, {  }>;
  bsr_sitesharedservices: WebAttribute<bsr_buildingdetails_Select, { bsr_sitesharedservices: bsr_sitesharedserviceschoice | null }, { bsr_sitesharedservices_formatted?: string }>;
  bsr_sitesharedservicesdetails: WebAttribute<bsr_buildingdetails_Select, { bsr_sitesharedservicesdetails: string | null }, {  }>;
  bsr_sitesharedservicesurl: WebAttribute<bsr_buildingdetails_Select, { bsr_sitesharedservicesurl: string | null }, {  }>;
  bsr_storeyuse: WebAttribute<bsr_buildingdetails_Select, { bsr_storeyuse: string | null }, {  }>;
  bsr_tellusaboutyourdrainageprecautions: WebAttribute<bsr_buildingdetails_Select, { bsr_tellusaboutyourdrainageprecautions: string | null }, {  }>;
  bsr_workdescription: WebAttribute<bsr_buildingdetails_Select, { bsr_workdescription: string | null }, {  }>;
  createdby_guid: WebAttribute<bsr_buildingdetails_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<bsr_buildingdetails_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<bsr_buildingdetails_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<bsr_buildingdetails_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<bsr_buildingdetails_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<bsr_buildingdetails_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<bsr_buildingdetails_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  overriddencreatedon: WebAttribute<bsr_buildingdetails_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<bsr_buildingdetails_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<bsr_buildingdetails_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<bsr_buildingdetails_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<bsr_buildingdetails_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<bsr_buildingdetails_Select, { statecode: bsr_buildingdetails_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<bsr_buildingdetails_Select, { statuscode: bsr_buildingdetails_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<bsr_buildingdetails_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<bsr_buildingdetails_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<bsr_buildingdetails_Select, { versionnumber: number | null }, {  }>;
}
interface bsr_buildingdetails_Filter {
  bsr_address1_city: string;
  bsr_address1_line1: string;
  bsr_address1_line2: string;
  bsr_address1_postalcode: string;
  bsr_bcapplicationid_guid: XQW.Guid;
  bsr_buildingaddressmanual: boolean;
  bsr_buildingcategory: bsr_buildingcategorychoice;
  bsr_buildingcontrollifecycle_guid: XQW.Guid;
  bsr_buildingdetailsid: XQW.Guid;
  bsr_buildingeasting: number;
  bsr_buildinghaveaddress: boolean;
  bsr_buildingid_guid: XQW.Guid;
  bsr_buildingnorthing: number;
  bsr_buildingregcompliance: string;
  bsr_buildingregcompliancecata: string;
  bsr_buildingregcompliancecatb: string;
  bsr_buildingregistrationnumber: string;
  bsr_buildoverwithin3mofcentrelineflow: boolean;
  bsr_changebuildingregcompliance: string;
  bsr_changeclientsignedstatement: string;
  bsr_changecompetencedeclaration: string;
  bsr_changeconstructioncontrolplan: string;
  bsr_changecontrolplan: string;
  bsr_changedrawingsandplans: string;
  bsr_changefireemergencyfiles: string;
  bsr_changeheight: any;
  bsr_changemorplan: string;
  bsr_changenonresidentialunits: number;
  bsr_changenumberofresidentialunits: number;
  bsr_changenumberstoreys: number;
  bsr_changeplannedbuildtime: number;
  bsr_changeplanningstatement: string;
  bsr_changeprimaryuse: bsr_primaryusechoice;
  bsr_changeuseofeachstory: string;
  bsr_changeworksdescription: string;
  bsr_clientsignedstatement: string;
  bsr_clientsignedstatementcata: string;
  bsr_clientsignedstatementcatb: string;
  bsr_competencedeclaration: string;
  bsr_competencedeclarationcata: string;
  bsr_competencedeclarationcatb: string;
  bsr_constructioncontrolplan: string;
  bsr_constructioncontrolplancata: string;
  bsr_constructioncontrolplancatb: string;
  bsr_currentheight: any;
  bsr_currentheightproposed: any;
  bsr_currentnonresidentialunits: number;
  bsr_currentnonresidentialunitsproposed: number;
  bsr_currentnumberofresidentialunits: number;
  bsr_currentnumberofresidentialunitsproposed: number;
  bsr_currentnumberstoreys: number;
  bsr_currentnumberstoreysproposed: number;
  bsr_currentplannedbuildtimeproposed: number;
  bsr_currentprimaryuse: bsr_primaryusechoice;
  bsr_currentstoreyuse: string;
  bsr_currentuseofeachstoryproposed: string;
  bsr_currentworksdescriptionproposed: string;
  bsr_drainageprecautions: boolean;
  bsr_drawingsandplans: string;
  bsr_drawingsandplanscata: string;
  bsr_drawingsandplanscatb: string;
  bsr_existingusecategory: bsr_existingusecategorychoice;
  bsr_existtypeworkproposal: bsr_existingusetypeofproposedworkchoic;
  bsr_fireemergencyfiles: string;
  bsr_fireemergencyfilescata: string;
  bsr_fireemergencyfilescatb: string;
  bsr_height: any;
  bsr_localenactment: string;
  bsr_localenactmentcompliance: string;
  bsr_morplan: string;
  bsr_morplancata: string;
  bsr_morplancatb: string;
  bsr_name: string;
  bsr_newdrainorsewer: boolean;
  bsr_nonhrb: boolean;
  bsr_numbernonresidentialunits: number;
  bsr_numberresidentialunits: number;
  bsr_numberstoreys: number;
  bsr_partialcompletion: bsr_partialcompletionchoice;
  bsr_partialcompletionstrategy: string;
  bsr_pgo: string;
  bsr_pgoreferencenumber: string;
  bsr_plannedbuildtime: number;
  bsr_planningreferencenumber: string;
  bsr_planningstatement: string;
  bsr_planningstatementcata: string;
  bsr_planningstatementcatb: string;
  bsr_primaryuse: bsr_primaryusechoice;
  bsr_proposedprimaryuse: bsr_primaryusechoice;
  bsr_sitelocationplan: string;
  bsr_sitesharedservices: bsr_sitesharedserviceschoice;
  bsr_sitesharedservicesdetails: string;
  bsr_sitesharedservicesurl: string;
  bsr_storeyuse: string;
  bsr_tellusaboutyourdrainageprecautions: string;
  bsr_workdescription: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: bsr_buildingdetails_statecode;
  statuscode: bsr_buildingdetails_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface bsr_buildingdetails_Expand {
}
interface bsr_buildingdetails_FormattedResult {
  bsr_bcapplicationid_formatted?: string;
  bsr_buildingcategory_formatted?: string;
  bsr_buildingcontrollifecycle_formatted?: string;
  bsr_buildingid_formatted?: string;
  bsr_changeprimaryuse_formatted?: string;
  bsr_currentprimaryuse_formatted?: string;
  bsr_existingusecategory_formatted?: string;
  bsr_existtypeworkproposal_formatted?: string;
  bsr_partialcompletion_formatted?: string;
  bsr_primaryuse_formatted?: string;
  bsr_proposedprimaryuse_formatted?: string;
  bsr_sitesharedservices_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface bsr_buildingdetails_Result extends bsr_buildingdetails_Base, bsr_buildingdetails_Relationships {
  "@odata.etag": string;
  bsr_bcapplicationid_guid: string | null;
  bsr_buildingcontrollifecycle_guid: string | null;
  bsr_buildingid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface bsr_buildingdetails_RelatedOne {
}
interface bsr_buildingdetails_RelatedMany {
}
interface WebEntitiesRetrieve {
  bsr_buildingdetailses: WebMappingRetrieve<bsr_buildingdetails_Select,bsr_buildingdetails_Expand,bsr_buildingdetails_Filter,bsr_buildingdetails_Fixed,bsr_buildingdetails_Result,bsr_buildingdetails_FormattedResult>;
}
interface WebEntitiesRelated {
  bsr_buildingdetailses: WebMappingRelated<bsr_buildingdetails_RelatedOne,bsr_buildingdetails_RelatedMany>;
}
interface WebEntitiesCUDA {
  bsr_buildingdetailses: WebMappingCUDA<bsr_buildingdetails_Create,bsr_buildingdetails_Update,bsr_buildingdetails_Select>;
}
