declare namespace Form.bsr_buildingcontrolapplication.Main {
  namespace Information {
    namespace Tabs {
      interface bcaa_changecontrol_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_5_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface bcaa_complcertstages_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_7_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface bcaa_completioncert_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_6_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface bcaa_payments_tab extends Xrm.SectionCollectionBase {
        get(name: "bcaa_submission_tab_section_8"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface bcaa_validation_tab extends Xrm.SectionCollectionBase {
        get(name: "bcaa_submission_tab_section_7"): Xrm.PageSection;
        get(name: "section_manage_building_control_approval_application"): Xrm.PageSection;
        get(name: "tab_5_section_7"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_4 extends Xrm.SectionCollectionBase {
        get(name: "_section_188"): Xrm.PageSection;
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: "tab_4_section_10"): Xrm.PageSection;
        get(name: "tab_4_section_11"): Xrm.PageSection;
        get(name: "tab_4_section_12"): Xrm.PageSection;
        get(name: "tab_4_section_13"): Xrm.PageSection;
        get(name: "tab_4_section_14"): Xrm.PageSection;
        get(name: "tab_4_section_4"): Xrm.PageSection;
        get(name: "tab_4_section_6"): Xrm.PageSection;
        get(name: "tab_4_section_7"): Xrm.PageSection;
        get(name: "tab_4_section_8"): Xrm.PageSection;
        get(name: "tab_4_section_9"): Xrm.PageSection;
        get(name: "tab_applicant_organisation"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_key_info extends Xrm.SectionCollectionBase {
        get(name: "null_section_4"): Xrm.PageSection;
        get(name: "section_application_submission"): Xrm.PageSection;
        get(name: "statusdetails"): Xrm.PageSection;
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: "tab_2_section_2"): Xrm.PageSection;
        get(name: "tab_key_info_section_11"): Xrm.PageSection;
        get(name: "{d103eaff-7e6e-4c0a-bf8b-3f8c87b278c1}_section_5"): Xrm.PageSection;
        get(name: "{d103eaff-7e6e-4c0a-bf8b-3f8c87b278c1}_section_6"): Xrm.PageSection;
        get(name: "{d103eaff-7e6e-4c0a-bf8b-3f8c87b278c1}_section_7"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_staged_application extends Xrm.SectionCollectionBase {
        get(name: "section_staged_application"): Xrm.PageSection;
        get(name: "tab_staged_application_section_3"): Xrm.PageSection;
        get(name: "tab_staged_application_section_4"): Xrm.PageSection;
        get(name: "tab_staged_application_section_5"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "bsr_addressline2"): Xrm.Attribute<string>;
      get(name: "bsr_addressline3"): Xrm.Attribute<string>;
      get(name: "bsr_adressline1"): Xrm.Attribute<string>;
      get(name: "bsr_applicantchanged"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_applicantchangeddate"): Xrm.DateAttribute;
      get(name: "bsr_applicantid"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_applicantorgchangedate"): Xrm.DateAttribute;
      get(name: "bsr_applicationvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_bcaacancellationreason"): Xrm.OptionSetAttribute<bsr_bcaacancellationreason>;
      get(name: "bsr_bcaacompletionreason"): Xrm.OptionSetAttribute<bsr_bcaacompletionreason>;
      get(name: "bsr_bcaainvalidreason"): Xrm.OptionSetAttribute<bsr_bcaainvalidreason>;
      get(name: "bsr_bcaareferencenumber"): Xrm.Attribute<string>;
      get(name: "bsr_buildingclientname"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "bsr_buildingcontrolapplicationstatus"): Xrm.OptionSetAttribute<bsr_buildingcontrolapplicationstatus>;
      get(name: "bsr_buildingprincipalcontractor"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "bsr_buildingprincipaldesigner"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "bsr_buildingregcompliance"): Xrm.Attribute<string>;
      get(name: "bsr_caseofficer"): Xrm.LookupAttribute<"systemuser">;
      get(name: "bsr_changeapplicantorganisation"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_changecontrolplan"): Xrm.Attribute<string>;
      get(name: "bsr_changeprincipalcontractor"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_changeprincipaldesigner"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_city"): Xrm.Attribute<string>;
      get(name: "bsr_clientchange"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_clientchangedate"): Xrm.DateAttribute;
      get(name: "bsr_clientcomplaints"): Xrm.Attribute<string>;
      get(name: "bsr_clientinspectmods"): Xrm.Attribute<string>;
      get(name: "bsr_clientinvestenforce"): Xrm.Attribute<string>;
      get(name: "bsr_clientnamedcontact"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_clientsignedstatement"): Xrm.Attribute<string>;
      get(name: "bsr_competencedeclaration"): Xrm.Attribute<string>;
      get(name: "bsr_constructioncontrolplan"): Xrm.Attribute<string>;
      get(name: "bsr_country"): Xrm.Attribute<string>;
      get(name: "bsr_declarationconfirmed"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_easting"): Xrm.NumberAttribute;
      get(name: "bsr_firecompliancedoc"): Xrm.Attribute<string>;
      get(name: "bsr_fireemergencyfiles"): Xrm.Attribute<string>;
      get(name: "bsr_firerescue"): Xrm.LookupAttribute<"account">;
      get(name: "bsr_havesiteaddress"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_informationrequest"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_informationrequesttracker"): Xrm.Attribute<string>;
      get(name: "bsr_invalidapplication"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_invalidapplicationemail"): Xrm.Attribute<string>;
      get(name: "bsr_isapplicantorgvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isapplicantvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_ischangeclientcontact"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_ischangeprincipalcontractorcontact"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_ischangeprincipaldesignercontact"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isclientcontactvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isclientorgvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_iscompletioncertificate"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isprincipalcontractorcontactvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isprincipalcontractororgvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isprincipaldesignercontactvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_isprincipaldesignerorgvalidated"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_issubsequentstagedapp"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_istheapplicanttheclient"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_localauthority"): Xrm.LookupAttribute<"account">;
      get(name: "bsr_mainbcaappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
      get(name: "bsr_morplan"): Xrm.Attribute<string>;
      get(name: "bsr_name"): Xrm.Attribute<string>;
      get(name: "bsr_northing"): Xrm.NumberAttribute;
      get(name: "bsr_numberofbuildings"): Xrm.NumberAttribute;
      get(name: "bsr_numberofstages"): Xrm.NumberAttribute;
      get(name: "bsr_organisationname"): Xrm.LookupAttribute<"account">;
      get(name: "bsr_parentbcaappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
      get(name: "bsr_partialcompletion"): Xrm.Attribute<any>;
      get(name: "bsr_partialcompletionstrategy"): Xrm.Attribute<string>;
      get(name: "bsr_postcode"): Xrm.Attribute<string>;
      get(name: "bsr_princcontractchangedate"): Xrm.DateAttribute;
      get(name: "bsr_princcontractcomplaints"): Xrm.Attribute<string>;
      get(name: "bsr_princcontractinspectionmods"): Xrm.Attribute<string>;
      get(name: "bsr_princcontractinvestenforce"): Xrm.Attribute<string>;
      get(name: "bsr_princdesignchangedate"): Xrm.DateAttribute;
      get(name: "bsr_princdesigncomplaints"): Xrm.Attribute<string>;
      get(name: "bsr_princdesigninspectmods"): Xrm.Attribute<string>;
      get(name: "bsr_princdesigninvestenforce"): Xrm.Attribute<string>;
      get(name: "bsr_principalcontractnamedcontact"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_principaldesignernamedcontact"): Xrm.LookupAttribute<"contact">;
      get(name: "bsr_principalsigneddecnotprovided"): Xrm.Attribute<string>;
      get(name: "bsr_raslastcheckeddate"): Xrm.DateAttribute;
      get(name: "bsr_regleadsupport"): Xrm.LookupAttribute<"systemuser">;
      get(name: "bsr_responsibleactorsscheme"): Xrm.OptionSetAttribute<bsr_responsibleactorsschemechoice>;
      get(name: "bsr_sewerageundertakerid"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "bsr_signedhandoverstatement"): Xrm.Attribute<string>;
      get(name: "bsr_stagedapplication"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_stagedworkdoc"): Xrm.Attribute<string>;
      get(name: "bsr_stagedworkstatement"): Xrm.Attribute<string>;
      get(name: "bsr_stagename"): Xrm.Attribute<string>;
      get(name: "bsr_stagenumber"): Xrm.NumberAttribute;
      get(name: "bsr_stageplannedenddate"): Xrm.DateAttribute;
      get(name: "bsr_stageplannedstartdate"): Xrm.DateAttribute;
      get(name: "bsr_stateprovince"): Xrm.Attribute<string>;
      get(name: "bsr_submissiondate"): Xrm.DateAttribute;
      get(name: "bsr_validapplication"): Xrm.OptionSetAttribute<boolean>;
      get(name: "bsr_validapplicationemail"): Xrm.Attribute<string>;
      get(name: "bsr_validationdate"): Xrm.DateAttribute;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_buildingdetails">;
      get(name: "Subgrid_new_2"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
      get(name: "Subgrid_new_3"): Xrm.SubGridControl<"bsr_drawingsandplans">;
      get(name: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_changerequest">;
      get(name: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_declarations">;
      get(name: "bsr_addressline2"): Xrm.StringControl;
      get(name: "bsr_addressline3"): Xrm.StringControl;
      get(name: "bsr_adressline1"): Xrm.StringControl;
      get(name: "bsr_applicantchanged"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_applicantchangeddate"): Xrm.DateControl;
      get(name: "bsr_applicantid"): Xrm.LookupControl<"contact">;
      get(name: "bsr_applicantorgchangedate"): Xrm.DateControl;
      get(name: "bsr_applicationvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_bcaacancellationreason"): Xrm.OptionSetControl<bsr_bcaacancellationreason>;
      get(name: "bsr_bcaacompletionreason"): Xrm.OptionSetControl<bsr_bcaacompletionreason>;
      get(name: "bsr_bcaainvalidreason"): Xrm.OptionSetControl<bsr_bcaainvalidreason>;
      get(name: "bsr_bcaareferencenumber"): Xrm.StringControl;
      get(name: "bsr_buildingclientname"): Xrm.LookupControl<"account" | "contact">;
      get(name: "bsr_buildingprincipalcontractor"): Xrm.LookupControl<"account" | "contact">;
      get(name: "bsr_buildingprincipaldesigner"): Xrm.LookupControl<"account" | "contact">;
      get(name: "bsr_buildingregcompliance"): Xrm.StringControl;
      get(name: "bsr_caseofficer"): Xrm.LookupControl<"systemuser">;
      get(name: "bsr_changeapplicantorganisation"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_changecontrol"): Xrm.SubGridControl<"bsr_changerequest">;
      get(name: "bsr_changecontrolplan"): Xrm.StringControl;
      get(name: "bsr_changeprincipalcontractor"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_changeprincipaldesigner"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_city"): Xrm.StringControl;
      get(name: "bsr_clientchange"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_clientchangedate"): Xrm.DateControl;
      get(name: "bsr_clientcomplaints"): Xrm.StringControl;
      get(name: "bsr_clientinspectmods"): Xrm.StringControl;
      get(name: "bsr_clientinvestenforce"): Xrm.StringControl;
      get(name: "bsr_clientnamedcontact"): Xrm.LookupControl<"contact">;
      get(name: "bsr_clientsignedstatement"): Xrm.StringControl;
      get(name: "bsr_competencedeclaration"): Xrm.StringControl;
      get(name: "bsr_completion_certificate_stages"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_completion_certifications"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_constructioncontrolplan"): Xrm.StringControl;
      get(name: "bsr_country"): Xrm.StringControl;
      get(name: "bsr_declarationconfirmed"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_easting"): Xrm.NumberControl;
      get(name: "bsr_firecompliancedoc"): Xrm.StringControl;
      get(name: "bsr_fireemergencyfiles"): Xrm.StringControl;
      get(name: "bsr_firerescue"): Xrm.LookupControl<"account">;
      get(name: "bsr_havesiteaddress"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_informationrequest"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_informationrequesttracker"): Xrm.StringControl;
      get(name: "bsr_invalidapplication"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_invalidapplicationemail"): Xrm.StringControl;
      get(name: "bsr_isapplicantorgvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isapplicantvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_ischangeclientcontact"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_ischangeprincipalcontractorcontact"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_ischangeprincipaldesignercontact"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isclientcontactvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isclientorgvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_iscompletioncertificate"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isprincipalcontractorcontactvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isprincipalcontractororgvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isprincipaldesignercontactvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_isprincipaldesignerorgvalidated"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_issubsequentstagedapp"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_istheapplicanttheclient"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_localauthority"): Xrm.LookupControl<"account">;
      get(name: "bsr_mainbcaappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_morplan"): Xrm.StringControl;
      get(name: "bsr_name"): Xrm.StringControl;
      get(name: "bsr_northing"): Xrm.NumberControl;
      get(name: "bsr_numberofbuildings"): Xrm.NumberControl;
      get(name: "bsr_numberofstages"): Xrm.NumberControl;
      get(name: "bsr_organisationname"): Xrm.LookupControl<"account">;
      get(name: "bsr_parentbcaappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
      get(name: "bsr_partialcompletion"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "bsr_partialcompletionstrategy"): Xrm.StringControl;
      get(name: "bsr_postcode"): Xrm.StringControl;
      get(name: "bsr_princcontractchangedate"): Xrm.DateControl;
      get(name: "bsr_princcontractcomplaints"): Xrm.StringControl;
      get(name: "bsr_princcontractinspectionmods"): Xrm.StringControl;
      get(name: "bsr_princcontractinvestenforce"): Xrm.StringControl;
      get(name: "bsr_princdesignchangedate"): Xrm.DateControl;
      get(name: "bsr_princdesigncomplaints"): Xrm.StringControl;
      get(name: "bsr_princdesigninspectmods"): Xrm.StringControl;
      get(name: "bsr_princdesigninvestenforce"): Xrm.StringControl;
      get(name: "bsr_principalcontractnamedcontact"): Xrm.LookupControl<"contact">;
      get(name: "bsr_principaldesignernamedcontact"): Xrm.LookupControl<"contact">;
      get(name: "bsr_principalsigneddecnotprovided"): Xrm.StringControl;
      get(name: "bsr_raslastcheckeddate"): Xrm.DateControl;
      get(name: "bsr_regleadsupport"): Xrm.LookupControl<"systemuser">;
      get(name: "bsr_responsibleactorsscheme"): Xrm.OptionSetControl<bsr_responsibleactorsschemechoice>;
      get(name: "bsr_sewerageundertakerid"): Xrm.LookupControl<"account" | "contact">;
      get(name: "bsr_signedhandoverstatement"): Xrm.StringControl;
      get(name: "bsr_stagedapplication"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_stagedworkdoc"): Xrm.StringControl;
      get(name: "bsr_stagedworkstatement"): Xrm.StringControl;
      get(name: "bsr_stagename"): Xrm.StringControl;
      get(name: "bsr_stagenumber"): Xrm.NumberControl;
      get(name: "bsr_stageplannedenddate"): Xrm.DateControl;
      get(name: "bsr_stageplannedstartdate"): Xrm.DateControl;
      get(name: "bsr_stateprovince"): Xrm.StringControl;
      get(name: "bsr_submissiondate"): Xrm.DateControl;
      get(name: "bsr_validapplication"): Xrm.OptionSetControl<boolean>;
      get(name: "bsr_validapplicationemail"): Xrm.StringControl;
      get(name: "bsr_validationdate"): Xrm.DateControl;
      get(name: "header_bsr_buildingcontrolapplicationstatus"): Xrm.OptionSetControl<bsr_buildingcontrolapplicationstatus>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "notescontrol1"): Xrm.BaseControl;
      get(name: "relatedpaymentrecords"): Xrm.SubGridControl<"bsr_payment">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "bcaa_changecontrol_tab"): Xrm.PageTab<Tabs.bcaa_changecontrol_tab>;
      get(name: "bcaa_complcertstages_tab"): Xrm.PageTab<Tabs.bcaa_complcertstages_tab>;
      get(name: "bcaa_completioncert_tab"): Xrm.PageTab<Tabs.bcaa_completioncert_tab>;
      get(name: "bcaa_payments_tab"): Xrm.PageTab<Tabs.bcaa_payments_tab>;
      get(name: "bcaa_validation_tab"): Xrm.PageTab<Tabs.bcaa_validation_tab>;
      get(name: "tab_4"): Xrm.PageTab<Tabs.tab_4>;
      get(name: "tab_key_info"): Xrm.PageTab<Tabs.tab_key_info>;
      get(name: "tab_staged_application"): Xrm.PageTab<Tabs.tab_staged_application>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "bsr_addressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_addressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_adressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_applicantchanged"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_applicantchangeddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_applicantid"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_applicantorgchangedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_applicationvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_bcaacancellationreason"): Xrm.OptionSetAttribute<bsr_bcaacancellationreason>;
    getAttribute(attributeName: "bsr_bcaacompletionreason"): Xrm.OptionSetAttribute<bsr_bcaacompletionreason>;
    getAttribute(attributeName: "bsr_bcaainvalidreason"): Xrm.OptionSetAttribute<bsr_bcaainvalidreason>;
    getAttribute(attributeName: "bsr_bcaareferencenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_buildingclientname"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "bsr_buildingcontrolapplicationstatus"): Xrm.OptionSetAttribute<bsr_buildingcontrolapplicationstatus>;
    getAttribute(attributeName: "bsr_buildingprincipalcontractor"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "bsr_buildingprincipaldesigner"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "bsr_buildingregcompliance"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_caseofficer"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "bsr_changeapplicantorganisation"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_changecontrolplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_changeprincipalcontractor"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_changeprincipaldesigner"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_city"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_clientchange"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_clientchangedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_clientcomplaints"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_clientinspectmods"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_clientinvestenforce"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_clientnamedcontact"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_clientsignedstatement"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_competencedeclaration"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_constructioncontrolplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_country"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_declarationconfirmed"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_easting"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_firecompliancedoc"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_fireemergencyfiles"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_firerescue"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "bsr_havesiteaddress"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_informationrequest"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_informationrequesttracker"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_invalidapplication"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_invalidapplicationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_isapplicantorgvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isapplicantvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_ischangeclientcontact"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_ischangeprincipalcontractorcontact"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_ischangeprincipaldesignercontact"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isclientcontactvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isclientorgvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_iscompletioncertificate"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isprincipalcontractorcontactvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isprincipalcontractororgvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isprincipaldesignercontactvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_isprincipaldesignerorgvalidated"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_issubsequentstagedapp"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_istheapplicanttheclient"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_localauthority"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "bsr_mainbcaappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
    getAttribute(attributeName: "bsr_morplan"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_northing"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_numberofbuildings"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_numberofstages"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_organisationname"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "bsr_parentbcaappid"): Xrm.LookupAttribute<"bsr_buildingcontrolapplication">;
    getAttribute(attributeName: "bsr_partialcompletion"): Xrm.Attribute<any>;
    getAttribute(attributeName: "bsr_partialcompletionstrategy"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_postcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princcontractchangedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_princcontractcomplaints"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princcontractinspectionmods"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princcontractinvestenforce"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princdesignchangedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_princdesigncomplaints"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princdesigninspectmods"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_princdesigninvestenforce"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_principalcontractnamedcontact"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_principaldesignernamedcontact"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "bsr_principalsigneddecnotprovided"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_raslastcheckeddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_regleadsupport"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "bsr_responsibleactorsscheme"): Xrm.OptionSetAttribute<bsr_responsibleactorsschemechoice>;
    getAttribute(attributeName: "bsr_sewerageundertakerid"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "bsr_signedhandoverstatement"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_stagedapplication"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_stagedworkdoc"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_stagedworkstatement"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_stagename"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_stagenumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "bsr_stageplannedenddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_stageplannedstartdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_stateprovince"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_submissiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "bsr_validapplication"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "bsr_validapplicationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "bsr_validationdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "Subgrid_new_1"): Xrm.SubGridControl<"bsr_buildingdetails">;
    getControl(controlName: "Subgrid_new_2"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "Subgrid_new_3"): Xrm.SubGridControl<"bsr_drawingsandplans">;
    getControl(controlName: "Subgrid_new_4"): Xrm.SubGridControl<"bsr_changerequest">;
    getControl(controlName: "Subgrid_new_5"): Xrm.SubGridControl<"bsr_declarations">;
    getControl(controlName: "bsr_addressline2"): Xrm.StringControl;
    getControl(controlName: "bsr_addressline3"): Xrm.StringControl;
    getControl(controlName: "bsr_adressline1"): Xrm.StringControl;
    getControl(controlName: "bsr_applicantchanged"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_applicantchangeddate"): Xrm.DateControl;
    getControl(controlName: "bsr_applicantid"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_applicantorgchangedate"): Xrm.DateControl;
    getControl(controlName: "bsr_applicationvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_bcaacancellationreason"): Xrm.OptionSetControl<bsr_bcaacancellationreason>;
    getControl(controlName: "bsr_bcaacompletionreason"): Xrm.OptionSetControl<bsr_bcaacompletionreason>;
    getControl(controlName: "bsr_bcaainvalidreason"): Xrm.OptionSetControl<bsr_bcaainvalidreason>;
    getControl(controlName: "bsr_bcaareferencenumber"): Xrm.StringControl;
    getControl(controlName: "bsr_buildingclientname"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "bsr_buildingprincipalcontractor"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "bsr_buildingprincipaldesigner"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "bsr_buildingregcompliance"): Xrm.StringControl;
    getControl(controlName: "bsr_caseofficer"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "bsr_changeapplicantorganisation"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_changecontrol"): Xrm.SubGridControl<"bsr_changerequest">;
    getControl(controlName: "bsr_changecontrolplan"): Xrm.StringControl;
    getControl(controlName: "bsr_changeprincipalcontractor"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_changeprincipaldesigner"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_city"): Xrm.StringControl;
    getControl(controlName: "bsr_clientchange"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_clientchangedate"): Xrm.DateControl;
    getControl(controlName: "bsr_clientcomplaints"): Xrm.StringControl;
    getControl(controlName: "bsr_clientinspectmods"): Xrm.StringControl;
    getControl(controlName: "bsr_clientinvestenforce"): Xrm.StringControl;
    getControl(controlName: "bsr_clientnamedcontact"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_clientsignedstatement"): Xrm.StringControl;
    getControl(controlName: "bsr_competencedeclaration"): Xrm.StringControl;
    getControl(controlName: "bsr_completion_certificate_stages"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_completion_certifications"): Xrm.SubGridControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_constructioncontrolplan"): Xrm.StringControl;
    getControl(controlName: "bsr_country"): Xrm.StringControl;
    getControl(controlName: "bsr_declarationconfirmed"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_easting"): Xrm.NumberControl;
    getControl(controlName: "bsr_firecompliancedoc"): Xrm.StringControl;
    getControl(controlName: "bsr_fireemergencyfiles"): Xrm.StringControl;
    getControl(controlName: "bsr_firerescue"): Xrm.LookupControl<"account">;
    getControl(controlName: "bsr_havesiteaddress"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_informationrequest"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_informationrequesttracker"): Xrm.StringControl;
    getControl(controlName: "bsr_invalidapplication"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_invalidapplicationemail"): Xrm.StringControl;
    getControl(controlName: "bsr_isapplicantorgvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isapplicantvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_ischangeclientcontact"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_ischangeprincipalcontractorcontact"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_ischangeprincipaldesignercontact"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isclientcontactvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isclientorgvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_iscompletioncertificate"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isprincipalcontractorcontactvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isprincipalcontractororgvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isprincipaldesignercontactvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_isprincipaldesignerorgvalidated"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_issubsequentstagedapp"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_istheapplicanttheclient"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_localauthority"): Xrm.LookupControl<"account">;
    getControl(controlName: "bsr_mainbcaappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_morplan"): Xrm.StringControl;
    getControl(controlName: "bsr_name"): Xrm.StringControl;
    getControl(controlName: "bsr_northing"): Xrm.NumberControl;
    getControl(controlName: "bsr_numberofbuildings"): Xrm.NumberControl;
    getControl(controlName: "bsr_numberofstages"): Xrm.NumberControl;
    getControl(controlName: "bsr_organisationname"): Xrm.LookupControl<"account">;
    getControl(controlName: "bsr_parentbcaappid"): Xrm.LookupControl<"bsr_buildingcontrolapplication">;
    getControl(controlName: "bsr_partialcompletion"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "bsr_partialcompletionstrategy"): Xrm.StringControl;
    getControl(controlName: "bsr_postcode"): Xrm.StringControl;
    getControl(controlName: "bsr_princcontractchangedate"): Xrm.DateControl;
    getControl(controlName: "bsr_princcontractcomplaints"): Xrm.StringControl;
    getControl(controlName: "bsr_princcontractinspectionmods"): Xrm.StringControl;
    getControl(controlName: "bsr_princcontractinvestenforce"): Xrm.StringControl;
    getControl(controlName: "bsr_princdesignchangedate"): Xrm.DateControl;
    getControl(controlName: "bsr_princdesigncomplaints"): Xrm.StringControl;
    getControl(controlName: "bsr_princdesigninspectmods"): Xrm.StringControl;
    getControl(controlName: "bsr_princdesigninvestenforce"): Xrm.StringControl;
    getControl(controlName: "bsr_principalcontractnamedcontact"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_principaldesignernamedcontact"): Xrm.LookupControl<"contact">;
    getControl(controlName: "bsr_principalsigneddecnotprovided"): Xrm.StringControl;
    getControl(controlName: "bsr_raslastcheckeddate"): Xrm.DateControl;
    getControl(controlName: "bsr_regleadsupport"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "bsr_responsibleactorsscheme"): Xrm.OptionSetControl<bsr_responsibleactorsschemechoice>;
    getControl(controlName: "bsr_sewerageundertakerid"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "bsr_signedhandoverstatement"): Xrm.StringControl;
    getControl(controlName: "bsr_stagedapplication"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_stagedworkdoc"): Xrm.StringControl;
    getControl(controlName: "bsr_stagedworkstatement"): Xrm.StringControl;
    getControl(controlName: "bsr_stagename"): Xrm.StringControl;
    getControl(controlName: "bsr_stagenumber"): Xrm.NumberControl;
    getControl(controlName: "bsr_stageplannedenddate"): Xrm.DateControl;
    getControl(controlName: "bsr_stageplannedstartdate"): Xrm.DateControl;
    getControl(controlName: "bsr_stateprovince"): Xrm.StringControl;
    getControl(controlName: "bsr_submissiondate"): Xrm.DateControl;
    getControl(controlName: "bsr_validapplication"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "bsr_validapplicationemail"): Xrm.StringControl;
    getControl(controlName: "bsr_validationdate"): Xrm.DateControl;
    getControl(controlName: "header_bsr_buildingcontrolapplicationstatus"): Xrm.OptionSetControl<bsr_buildingcontrolapplicationstatus>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "notescontrol1"): Xrm.BaseControl;
    getControl(controlName: "relatedpaymentrecords"): Xrm.SubGridControl<"bsr_payment">;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
