interface bsr_buildingcontrolapplication_Base extends WebEntity {
  bsr_addressline2?: string | null;
  bsr_addressline3?: string | null;
  bsr_adressline1?: string | null;
  bsr_applicantchanged?: boolean | null;
  bsr_applicantchangeddate?: Date | null;
  bsr_applicationid?: string | null;
  bsr_applicationname?: string | null;
  bsr_applicationvalidated?: boolean | null;
  bsr_bcaacancellationreason?: bsr_bcaacancellationreason | null;
  bsr_bcaacompletionreason?: bsr_bcaacompletionreason | null;
  bsr_bcaainvalidreason?: bsr_bcaainvalidreason | null;
  bsr_bcaareferencenumber?: string | null;
  bsr_buildingcontrolapplicationid?: string | null;
  bsr_buildingcontrolapplicationstatus?: bsr_buildingcontrolapplicationstatus | null;
  bsr_changeprincipalcontractor?: boolean | null;
  bsr_changeprincipaldesigner?: boolean | null;
  bsr_city?: string | null;
  bsr_clientchange?: boolean | null;
  bsr_clientchangedate?: Date | null;
  bsr_clientcomplaints?: string | null;
  bsr_clientinspectmods?: string | null;
  bsr_clientinvestenforce?: string | null;
  bsr_clientsignedstatement?: string | null;
  bsr_country?: string | null;
  bsr_currentdate?: Date | null;
  bsr_declarationconfirmed?: boolean | null;
  bsr_easting?: number | null;
  bsr_haverefnumber?: bsr_doyouhavebuildingrefcode | null;
  bsr_havesiteaddress?: boolean | null;
  bsr_hrbtypecode?: bsr_hrbtypechoice | null;
  bsr_informationrequest?: boolean | null;
  bsr_informationrequesttracker?: string | null;
  bsr_invalidapplication?: boolean | null;
  bsr_invalidapplicationemail?: string | null;
  bsr_isclientcontactvalidated?: boolean | null;
  bsr_isclientorgvalidated?: boolean | null;
  bsr_isprincipalcontractorcontactvalidated?: boolean | null;
  bsr_isprincipalcontractororgvalidated?: boolean | null;
  bsr_isprincipaldesignercontactvalidated?: boolean | null;
  bsr_isprincipaldesignerorgvalidated?: boolean | null;
  bsr_issubsequentstagedapp?: boolean | null;
  bsr_istheapplicanttheclient?: boolean | null;
  bsr_name?: string | null;
  bsr_northing?: number | null;
  bsr_numberofbuildings?: number | null;
  bsr_numberofstages?: number | null;
  bsr_postcode?: string | null;
  bsr_princcontractchangedate?: Date | null;
  bsr_princcontractcomplaints?: string | null;
  bsr_princcontractinspectionmods?: string | null;
  bsr_princcontractinvestenforce?: string | null;
  bsr_princdesignchangedate?: Date | null;
  bsr_princdesigncomplaints?: string | null;
  bsr_princdesigninspectmods?: string | null;
  bsr_princdesigninvestenforce?: string | null;
  bsr_raslastcheckeddate?: Date | null;
  bsr_responsibleactorsscheme?: bsr_responsibleactorsschemechoice | null;
  bsr_stagedapplication?: boolean | null;
  bsr_stagedinformationrequest?: boolean | null;
  bsr_stagedinformationrequesttracker?: string | null;
  bsr_stagedinvalidapplication?: boolean | null;
  bsr_stagedinvalidapplicationemail?: string | null;
  bsr_stagedvalidapplication?: boolean | null;
  bsr_stagedvalidapplicationemail?: string | null;
  bsr_stagedvalidationdate?: Date | null;
  bsr_stagedworkdoc?: string | null;
  bsr_stagedworkstatement?: string | null;
  bsr_stagename?: string | null;
  bsr_stagenumber?: number | null;
  bsr_stageplannedenddate?: Date | null;
  bsr_stageplannedstartdate?: Date | null;
  bsr_stateprovince?: string | null;
  bsr_submissiondate?: Date | null;
  bsr_validapplication?: boolean | null;
  bsr_validapplicationemail?: string | null;
  bsr_validationdate?: Date | null;
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  statecode?: bsr_buildingcontrolapplication_statecode | null;
  statuscode?: bsr_buildingcontrolapplication_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface bsr_buildingcontrolapplication_Relationships {
  bsr_bsr_buildingcontrolapplication_mainbcaapp?: bsr_buildingcontrolapplication_Result[] | null;
  bsr_buildingdetails_bcapplicationid?: bsr_buildingdetails_Result[] | null;
}
interface bsr_buildingcontrolapplication extends bsr_buildingcontrolapplication_Base, bsr_buildingcontrolapplication_Relationships {
  bsr_applicantid_bind$contacts?: string | null;
  bsr_buildingclientname_account_bind$accounts?: string | null;
  bsr_buildingclientname_contact_bind$contacts?: string | null;
  bsr_buildingprincipalcontractor_account_bind$accounts?: string | null;
  bsr_buildingprincipalcontractor_contact_bind$contacts?: string | null;
  bsr_buildingprincipaldesigner_account_bind$accounts?: string | null;
  bsr_buildingprincipaldesigner_contact_bind$contacts?: string | null;
  bsr_caseofficer_bind$systemusers?: string | null;
  bsr_clientnamedcontact_bind$contacts?: string | null;
  bsr_firerescue_bind$accounts?: string | null;
  bsr_localauthority_bind$accounts?: string | null;
  bsr_mainbcaappid_bind$bsr_buildingcontrolapplications?: string | null;
  bsr_organisationname_bind$accounts?: string | null;
  bsr_principalcontractnamedcontact_bind$contacts?: string | null;
  bsr_principaldesignernamedcontact_bind$contacts?: string | null;
  bsr_regleadsupport_bind$systemusers?: string | null;
  bsr_sewerageundertakerid_account_bind$accounts?: string | null;
  bsr_sewerageundertakerid_contact_bind$contacts?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface bsr_buildingcontrolapplication_Create extends bsr_buildingcontrolapplication {
}
interface bsr_buildingcontrolapplication_Update extends bsr_buildingcontrolapplication {
}
interface bsr_buildingcontrolapplication_Select {
  bsr_addressline2: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_addressline2: string | null }, {  }>;
  bsr_addressline3: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_addressline3: string | null }, {  }>;
  bsr_adressline1: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_adressline1: string | null }, {  }>;
  bsr_applicantchanged: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicantchanged: boolean | null }, {  }>;
  bsr_applicantchangeddate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicantchangeddate: Date | null }, { bsr_applicantchangeddate_formatted?: string }>;
  bsr_applicantid_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicantid_guid: string | null }, { bsr_applicantid_formatted?: string }>;
  bsr_applicationid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicationid: string | null }, {  }>;
  bsr_applicationname: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicationname: string | null }, {  }>;
  bsr_applicationvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_applicationvalidated: boolean | null }, {  }>;
  bsr_bcaacancellationreason: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_bcaacancellationreason: bsr_bcaacancellationreason | null }, { bsr_bcaacancellationreason_formatted?: string }>;
  bsr_bcaacompletionreason: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_bcaacompletionreason: bsr_bcaacompletionreason | null }, { bsr_bcaacompletionreason_formatted?: string }>;
  bsr_bcaainvalidreason: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_bcaainvalidreason: bsr_bcaainvalidreason | null }, { bsr_bcaainvalidreason_formatted?: string }>;
  bsr_bcaareferencenumber: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_bcaareferencenumber: string | null }, {  }>;
  bsr_buildingclientname_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_buildingclientname_guid: string | null }, { bsr_buildingclientname_formatted?: string }>;
  bsr_buildingcontrolapplicationid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_buildingcontrolapplicationid: string | null }, {  }>;
  bsr_buildingcontrolapplicationstatus: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_buildingcontrolapplicationstatus: bsr_buildingcontrolapplicationstatus | null }, { bsr_buildingcontrolapplicationstatus_formatted?: string }>;
  bsr_buildingprincipalcontractor_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_buildingprincipalcontractor_guid: string | null }, { bsr_buildingprincipalcontractor_formatted?: string }>;
  bsr_buildingprincipaldesigner_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_buildingprincipaldesigner_guid: string | null }, { bsr_buildingprincipaldesigner_formatted?: string }>;
  bsr_caseofficer_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_caseofficer_guid: string | null }, { bsr_caseofficer_formatted?: string }>;
  bsr_changeprincipalcontractor: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_changeprincipalcontractor: boolean | null }, {  }>;
  bsr_changeprincipaldesigner: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_changeprincipaldesigner: boolean | null }, {  }>;
  bsr_city: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_city: string | null }, {  }>;
  bsr_clientchange: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientchange: boolean | null }, {  }>;
  bsr_clientchangedate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientchangedate: Date | null }, { bsr_clientchangedate_formatted?: string }>;
  bsr_clientcomplaints: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientcomplaints: string | null }, {  }>;
  bsr_clientinspectmods: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientinspectmods: string | null }, {  }>;
  bsr_clientinvestenforce: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientinvestenforce: string | null }, {  }>;
  bsr_clientnamedcontact_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientnamedcontact_guid: string | null }, { bsr_clientnamedcontact_formatted?: string }>;
  bsr_clientsignedstatement: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_clientsignedstatement: string | null }, {  }>;
  bsr_country: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_country: string | null }, {  }>;
  bsr_currentdate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_currentdate: Date | null }, { bsr_currentdate_formatted?: string }>;
  bsr_declarationconfirmed: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_declarationconfirmed: boolean | null }, {  }>;
  bsr_easting: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_easting: number | null }, {  }>;
  bsr_firerescue_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_firerescue_guid: string | null }, { bsr_firerescue_formatted?: string }>;
  bsr_haverefnumber: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_haverefnumber: bsr_doyouhavebuildingrefcode | null }, { bsr_haverefnumber_formatted?: string }>;
  bsr_havesiteaddress: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_havesiteaddress: boolean | null }, {  }>;
  bsr_hrbtypecode: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_hrbtypecode: bsr_hrbtypechoice | null }, { bsr_hrbtypecode_formatted?: string }>;
  bsr_informationrequest: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_informationrequest: boolean | null }, {  }>;
  bsr_informationrequesttracker: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_informationrequesttracker: string | null }, {  }>;
  bsr_invalidapplication: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_invalidapplication: boolean | null }, {  }>;
  bsr_invalidapplicationemail: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_invalidapplicationemail: string | null }, {  }>;
  bsr_isclientcontactvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isclientcontactvalidated: boolean | null }, {  }>;
  bsr_isclientorgvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isclientorgvalidated: boolean | null }, {  }>;
  bsr_isprincipalcontractorcontactvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isprincipalcontractorcontactvalidated: boolean | null }, {  }>;
  bsr_isprincipalcontractororgvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isprincipalcontractororgvalidated: boolean | null }, {  }>;
  bsr_isprincipaldesignercontactvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isprincipaldesignercontactvalidated: boolean | null }, {  }>;
  bsr_isprincipaldesignerorgvalidated: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_isprincipaldesignerorgvalidated: boolean | null }, {  }>;
  bsr_issubsequentstagedapp: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_issubsequentstagedapp: boolean | null }, {  }>;
  bsr_istheapplicanttheclient: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_istheapplicanttheclient: boolean | null }, {  }>;
  bsr_localauthority_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_localauthority_guid: string | null }, { bsr_localauthority_formatted?: string }>;
  bsr_mainbcaappid_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_mainbcaappid_guid: string | null }, { bsr_mainbcaappid_formatted?: string }>;
  bsr_name: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_name: string | null }, {  }>;
  bsr_northing: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_northing: number | null }, {  }>;
  bsr_numberofbuildings: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_numberofbuildings: number | null }, {  }>;
  bsr_numberofstages: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_numberofstages: number | null }, {  }>;
  bsr_organisationname_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_organisationname_guid: string | null }, { bsr_organisationname_formatted?: string }>;
  bsr_postcode: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_postcode: string | null }, {  }>;
  bsr_princcontractchangedate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princcontractchangedate: Date | null }, { bsr_princcontractchangedate_formatted?: string }>;
  bsr_princcontractcomplaints: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princcontractcomplaints: string | null }, {  }>;
  bsr_princcontractinspectionmods: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princcontractinspectionmods: string | null }, {  }>;
  bsr_princcontractinvestenforce: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princcontractinvestenforce: string | null }, {  }>;
  bsr_princdesignchangedate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princdesignchangedate: Date | null }, { bsr_princdesignchangedate_formatted?: string }>;
  bsr_princdesigncomplaints: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princdesigncomplaints: string | null }, {  }>;
  bsr_princdesigninspectmods: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princdesigninspectmods: string | null }, {  }>;
  bsr_princdesigninvestenforce: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_princdesigninvestenforce: string | null }, {  }>;
  bsr_principalcontractnamedcontact_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_principalcontractnamedcontact_guid: string | null }, { bsr_principalcontractnamedcontact_formatted?: string }>;
  bsr_principaldesignernamedcontact_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_principaldesignernamedcontact_guid: string | null }, { bsr_principaldesignernamedcontact_formatted?: string }>;
  bsr_raslastcheckeddate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_raslastcheckeddate: Date | null }, { bsr_raslastcheckeddate_formatted?: string }>;
  bsr_regleadsupport_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_regleadsupport_guid: string | null }, { bsr_regleadsupport_formatted?: string }>;
  bsr_responsibleactorsscheme: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_responsibleactorsscheme: bsr_responsibleactorsschemechoice | null }, { bsr_responsibleactorsscheme_formatted?: string }>;
  bsr_sewerageundertakerid_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_sewerageundertakerid_guid: string | null }, { bsr_sewerageundertakerid_formatted?: string }>;
  bsr_stagedapplication: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedapplication: boolean | null }, {  }>;
  bsr_stagedinformationrequest: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedinformationrequest: boolean | null }, {  }>;
  bsr_stagedinformationrequesttracker: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedinformationrequesttracker: string | null }, {  }>;
  bsr_stagedinvalidapplication: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedinvalidapplication: boolean | null }, {  }>;
  bsr_stagedinvalidapplicationemail: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedinvalidapplicationemail: string | null }, {  }>;
  bsr_stagedvalidapplication: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedvalidapplication: boolean | null }, {  }>;
  bsr_stagedvalidapplicationemail: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedvalidapplicationemail: string | null }, {  }>;
  bsr_stagedvalidationdate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedvalidationdate: Date | null }, { bsr_stagedvalidationdate_formatted?: string }>;
  bsr_stagedworkdoc: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedworkdoc: string | null }, {  }>;
  bsr_stagedworkstatement: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagedworkstatement: string | null }, {  }>;
  bsr_stagename: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagename: string | null }, {  }>;
  bsr_stagenumber: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stagenumber: number | null }, {  }>;
  bsr_stageplannedenddate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stageplannedenddate: Date | null }, { bsr_stageplannedenddate_formatted?: string }>;
  bsr_stageplannedstartdate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stageplannedstartdate: Date | null }, { bsr_stageplannedstartdate_formatted?: string }>;
  bsr_stateprovince: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_stateprovince: string | null }, {  }>;
  bsr_submissiondate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_submissiondate: Date | null }, { bsr_submissiondate_formatted?: string }>;
  bsr_validapplication: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_validapplication: boolean | null }, {  }>;
  bsr_validapplicationemail: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_validapplicationemail: string | null }, {  }>;
  bsr_validationdate: WebAttribute<bsr_buildingcontrolapplication_Select, { bsr_validationdate: Date | null }, { bsr_validationdate_formatted?: string }>;
  createdby_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<bsr_buildingcontrolapplication_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<bsr_buildingcontrolapplication_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<bsr_buildingcontrolapplication_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  overriddencreatedon: WebAttribute<bsr_buildingcontrolapplication_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<bsr_buildingcontrolapplication_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<bsr_buildingcontrolapplication_Select, { statecode: bsr_buildingcontrolapplication_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<bsr_buildingcontrolapplication_Select, { statuscode: bsr_buildingcontrolapplication_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<bsr_buildingcontrolapplication_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<bsr_buildingcontrolapplication_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<bsr_buildingcontrolapplication_Select, { versionnumber: number | null }, {  }>;
}
interface bsr_buildingcontrolapplication_Filter {
  bsr_addressline2: string;
  bsr_addressline3: string;
  bsr_adressline1: string;
  bsr_applicantchanged: boolean;
  bsr_applicantchangeddate: Date;
  bsr_applicantid_guid: XQW.Guid;
  bsr_applicationid: string;
  bsr_applicationname: string;
  bsr_applicationvalidated: boolean;
  bsr_bcaacancellationreason: bsr_bcaacancellationreason;
  bsr_bcaacompletionreason: bsr_bcaacompletionreason;
  bsr_bcaainvalidreason: bsr_bcaainvalidreason;
  bsr_bcaareferencenumber: string;
  bsr_buildingclientname_guid: XQW.Guid;
  bsr_buildingcontrolapplicationid: XQW.Guid;
  bsr_buildingcontrolapplicationstatus: bsr_buildingcontrolapplicationstatus;
  bsr_buildingprincipalcontractor_guid: XQW.Guid;
  bsr_buildingprincipaldesigner_guid: XQW.Guid;
  bsr_caseofficer_guid: XQW.Guid;
  bsr_changeprincipalcontractor: boolean;
  bsr_changeprincipaldesigner: boolean;
  bsr_city: string;
  bsr_clientchange: boolean;
  bsr_clientchangedate: Date;
  bsr_clientcomplaints: string;
  bsr_clientinspectmods: string;
  bsr_clientinvestenforce: string;
  bsr_clientnamedcontact_guid: XQW.Guid;
  bsr_clientsignedstatement: string;
  bsr_country: string;
  bsr_currentdate: Date;
  bsr_declarationconfirmed: boolean;
  bsr_easting: number;
  bsr_firerescue_guid: XQW.Guid;
  bsr_haverefnumber: bsr_doyouhavebuildingrefcode;
  bsr_havesiteaddress: boolean;
  bsr_hrbtypecode: bsr_hrbtypechoice;
  bsr_informationrequest: boolean;
  bsr_informationrequesttracker: string;
  bsr_invalidapplication: boolean;
  bsr_invalidapplicationemail: string;
  bsr_isclientcontactvalidated: boolean;
  bsr_isclientorgvalidated: boolean;
  bsr_isprincipalcontractorcontactvalidated: boolean;
  bsr_isprincipalcontractororgvalidated: boolean;
  bsr_isprincipaldesignercontactvalidated: boolean;
  bsr_isprincipaldesignerorgvalidated: boolean;
  bsr_issubsequentstagedapp: boolean;
  bsr_istheapplicanttheclient: boolean;
  bsr_localauthority_guid: XQW.Guid;
  bsr_mainbcaappid_guid: XQW.Guid;
  bsr_name: string;
  bsr_northing: number;
  bsr_numberofbuildings: number;
  bsr_numberofstages: number;
  bsr_organisationname_guid: XQW.Guid;
  bsr_postcode: string;
  bsr_princcontractchangedate: Date;
  bsr_princcontractcomplaints: string;
  bsr_princcontractinspectionmods: string;
  bsr_princcontractinvestenforce: string;
  bsr_princdesignchangedate: Date;
  bsr_princdesigncomplaints: string;
  bsr_princdesigninspectmods: string;
  bsr_princdesigninvestenforce: string;
  bsr_principalcontractnamedcontact_guid: XQW.Guid;
  bsr_principaldesignernamedcontact_guid: XQW.Guid;
  bsr_raslastcheckeddate: Date;
  bsr_regleadsupport_guid: XQW.Guid;
  bsr_responsibleactorsscheme: bsr_responsibleactorsschemechoice;
  bsr_sewerageundertakerid_guid: XQW.Guid;
  bsr_stagedapplication: boolean;
  bsr_stagedinformationrequest: boolean;
  bsr_stagedinformationrequesttracker: string;
  bsr_stagedinvalidapplication: boolean;
  bsr_stagedinvalidapplicationemail: string;
  bsr_stagedvalidapplication: boolean;
  bsr_stagedvalidapplicationemail: string;
  bsr_stagedvalidationdate: Date;
  bsr_stagedworkdoc: string;
  bsr_stagedworkstatement: string;
  bsr_stagename: string;
  bsr_stagenumber: number;
  bsr_stageplannedenddate: Date;
  bsr_stageplannedstartdate: Date;
  bsr_stateprovince: string;
  bsr_submissiondate: Date;
  bsr_validapplication: boolean;
  bsr_validapplicationemail: string;
  bsr_validationdate: Date;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: bsr_buildingcontrolapplication_statecode;
  statuscode: bsr_buildingcontrolapplication_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface bsr_buildingcontrolapplication_Expand {
  bsr_bsr_buildingcontrolapplication_mainbcaapp: WebExpand<bsr_buildingcontrolapplication_Expand, bsr_buildingcontrolapplication_Select, bsr_buildingcontrolapplication_Filter, { bsr_bsr_buildingcontrolapplication_mainbcaapp: bsr_buildingcontrolapplication_Result[] }>;
  bsr_buildingdetails_bcapplicationid: WebExpand<bsr_buildingcontrolapplication_Expand, bsr_buildingdetails_Select, bsr_buildingdetails_Filter, { bsr_buildingdetails_bcapplicationid: bsr_buildingdetails_Result[] }>;
  bsr_mainbcaappid: WebExpand<bsr_buildingcontrolapplication_Expand, bsr_buildingcontrolapplication_Select, bsr_buildingcontrolapplication_Filter, { bsr_mainbcaappid: bsr_buildingcontrolapplication_Result }>;
}
interface bsr_buildingcontrolapplication_FormattedResult {
  bsr_applicantchangeddate_formatted?: string;
  bsr_applicantid_formatted?: string;
  bsr_bcaacancellationreason_formatted?: string;
  bsr_bcaacompletionreason_formatted?: string;
  bsr_bcaainvalidreason_formatted?: string;
  bsr_buildingclientname_formatted?: string;
  bsr_buildingcontrolapplicationstatus_formatted?: string;
  bsr_buildingprincipalcontractor_formatted?: string;
  bsr_buildingprincipaldesigner_formatted?: string;
  bsr_caseofficer_formatted?: string;
  bsr_clientchangedate_formatted?: string;
  bsr_clientnamedcontact_formatted?: string;
  bsr_currentdate_formatted?: string;
  bsr_firerescue_formatted?: string;
  bsr_haverefnumber_formatted?: string;
  bsr_hrbtypecode_formatted?: string;
  bsr_localauthority_formatted?: string;
  bsr_mainbcaappid_formatted?: string;
  bsr_organisationname_formatted?: string;
  bsr_princcontractchangedate_formatted?: string;
  bsr_princdesignchangedate_formatted?: string;
  bsr_principalcontractnamedcontact_formatted?: string;
  bsr_principaldesignernamedcontact_formatted?: string;
  bsr_raslastcheckeddate_formatted?: string;
  bsr_regleadsupport_formatted?: string;
  bsr_responsibleactorsscheme_formatted?: string;
  bsr_sewerageundertakerid_formatted?: string;
  bsr_stagedvalidationdate_formatted?: string;
  bsr_stageplannedenddate_formatted?: string;
  bsr_stageplannedstartdate_formatted?: string;
  bsr_submissiondate_formatted?: string;
  bsr_validationdate_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface bsr_buildingcontrolapplication_Result extends bsr_buildingcontrolapplication_Base, bsr_buildingcontrolapplication_Relationships {
  "@odata.etag": string;
  bsr_applicantid_guid: string | null;
  bsr_buildingclientname_guid: string | null;
  bsr_buildingprincipalcontractor_guid: string | null;
  bsr_buildingprincipaldesigner_guid: string | null;
  bsr_caseofficer_guid: string | null;
  bsr_clientnamedcontact_guid: string | null;
  bsr_firerescue_guid: string | null;
  bsr_localauthority_guid: string | null;
  bsr_mainbcaappid_guid: string | null;
  bsr_organisationname_guid: string | null;
  bsr_principalcontractnamedcontact_guid: string | null;
  bsr_principaldesignernamedcontact_guid: string | null;
  bsr_regleadsupport_guid: string | null;
  bsr_sewerageundertakerid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface bsr_buildingcontrolapplication_RelatedOne {
  bsr_mainbcaappid: WebMappingRetrieve<bsr_buildingcontrolapplication_Select,bsr_buildingcontrolapplication_Expand,bsr_buildingcontrolapplication_Filter,bsr_buildingcontrolapplication_Fixed,bsr_buildingcontrolapplication_Result,bsr_buildingcontrolapplication_FormattedResult>;
}
interface bsr_buildingcontrolapplication_RelatedMany {
  bsr_bsr_buildingcontrolapplication_mainbcaapp: WebMappingRetrieve<bsr_buildingcontrolapplication_Select,bsr_buildingcontrolapplication_Expand,bsr_buildingcontrolapplication_Filter,bsr_buildingcontrolapplication_Fixed,bsr_buildingcontrolapplication_Result,bsr_buildingcontrolapplication_FormattedResult>;
  bsr_buildingdetails_bcapplicationid: WebMappingRetrieve<bsr_buildingdetails_Select,bsr_buildingdetails_Expand,bsr_buildingdetails_Filter,bsr_buildingdetails_Fixed,bsr_buildingdetails_Result,bsr_buildingdetails_FormattedResult>;
}
interface WebEntitiesRetrieve {
  bsr_buildingcontrolapplications: WebMappingRetrieve<bsr_buildingcontrolapplication_Select,bsr_buildingcontrolapplication_Expand,bsr_buildingcontrolapplication_Filter,bsr_buildingcontrolapplication_Fixed,bsr_buildingcontrolapplication_Result,bsr_buildingcontrolapplication_FormattedResult>;
}
interface WebEntitiesRelated {
  bsr_buildingcontrolapplications: WebMappingRelated<bsr_buildingcontrolapplication_RelatedOne,bsr_buildingcontrolapplication_RelatedMany>;
}
interface WebEntitiesCUDA {
  bsr_buildingcontrolapplications: WebMappingCUDA<bsr_buildingcontrolapplication_Create,bsr_buildingcontrolapplication_Update,bsr_buildingcontrolapplication_Select>;
}
